# actions:
#   match alignments to RE sites and fragments to characterize inserts
#   apply various alignment and SV quality filters and error correction mechanisms
#       see hf3_tools Rust crate for details
# input:
#   NAME_BAM_FILE, as generated by `align` step 
#   FILERING_SITES_FILE, as generated by `locate/tabulate_endpoints.sh`
# output:
#   NAME_BAM_FILE with added insert-level tags

TMP_BAM_FILE=${TMP_FILE_PREFIX_SMALL}.name.tmp.bam
rm -f ${TMP_BAM_FILE}

echo "analyzing insert-level properties (RE sites and sizes) to set filtering tags"
samtools view --threads ${SAMTOOLS_CPU} -h ${NAME_BAM_FILE} | 
${MDI_DIR}/bin/hf3_tools analyze_inserts | 
samtools view --threads ${SAMTOOLS_CPU} -b -o ${TMP_BAM_FILE} -
checkPipe

# replace original BAM with filtered version
echo "replacing original name BAM file with updated BAM"
mv -f ${TMP_BAM_FILE} ${NAME_BAM_FILE}
checkPipe

echo "done"
