---
pipeline:
    name: combine
    description: "Concatenate two reference genomes for use with mixed-species samples"
    version: v0.0.1
actions:
    _global:
        environment: hf3Main
        condaFamilies:
            - base
            - main
    genomes:
        order: 1
        optionFamilies:
            - combine-genomes
            - digestion
        resources:
            required:
                total-ram: 8G
            recommended: 
                n-cpu: 1
                ram-per-cpu: 8G
        job-manager:
            recommended:
                time-limit: 4:00:00
        description: "concatenate two reference genomes for use with mixed-species samples"
# container:
#     supported: false    # set to true if you maintain a container registry for this pipeline [false]
#     registry:  ghcr.io  # domain name of your OCI-compatible, oras-accessible, container registry [ghcr.io]
#     owner:     wilsontelab # REQUIRED: the name of the owner, e.g., user or organization, at 'registry'
#     installer: apt-get  # the installer program used by the container OS, typically apt-get or yum [apt-get]
