use strict;
use warnings;

# action:
#   describe the match/SNV/indel combinations of single-alignment end-to-end RE fragments
#       in HiFiRe3, these are always PacBio HiFi reads, which are implicitly duplex and thus not stranded
#       for now, tabulate even those with too-low fragment coverage
#   use an efficient fragment index to count and sort unique combinations
#   work is parallelized by chromosome for speed gains and sorting efficiency
#   this script is only applicable to sequencing platforms where HAS_BASE_ACCURACY=TRUE
#   match/SNV/indel combinations in an alignment are described by:
#       readOffset = number of bases to place the alignment onto the read relative to its leftmost reference end
#                    thus, the number of bases clipped from the read upstream of the first vaTag : operation
#       vaTag = reformatted cs:Z: tag, in reference strand orientation
#           see va_tag_utils.pl for a detailed description of the va tag
#           all vaTag coordinate and base values are relative to the top genome strand
#       qsTag = tag that carries boolean passed-quality operations in parallel to vaTag, where qsTag value are:
#               vaTag : operations = always 1 = passed quality (must be high or base alignment would have failed)
#               vaTag alignment length  > 0 = 0|1 indicating if the average quality of the variant read bases is >= MIN_SNV_INDEL_QUAL
#               vaTag alignment length == 0 = 0|1 indicating if the average quality of the two bases flanking the isolated deletion is >= MIN_SNV_INDEL_QUAL
#   to facilitate construction of base pileups, bottom strand alignments are reverse complemented to match the reference strand, including:
#       SEQ and QUAL
#       XX tags that carry heteroduplex information
#          note that cs and thus va tags are always in reference strand orientation
#   a hash is used to track the unique alignments encountered for each bin as:
#       zeroPaddedLeftPos1,zeroPaddedRightPos1,readOffset,vaTag,qsTag
#   where the following hash components are used for sorting but omitted from the final output:
#       leftPos1  = the lowest  reference strand coordinate of the alignment, corresponding to the first vaTag : operation
#       rightPos1 = the highest reference strand coordinate of the alignment
#           zeroPadded postions support simple and efficient lexical sorting of positions within bins
#   the indexing strategy exploits threads, loops, and numeric indices to pre-sort by:
#       chromIndex1 => binIndex0
#       where binIndex0 bins alignment 5' ends by leftPos1 for a first round of sorting into groups
#   indexing is an aggregating action, so read/event identifiers are lost in the index
#   unlike for SVs, no attempt is made to retain a list to allow SNV/indels to be correlated to source reads because:
#       the main utility would be for purging duplex redundancy, and ONT is never used for SNV tracking
#       alignment-level quality filters have already been enforced
#       other essential alignment metadata are present in the index
# input:
#   SITE_SAM files generated by `analyze fragments`, one file per chromosome
# output:
#   alignment_maps = one row per unique read alignment, one file per chromosome
#   base_qualities = counts of SNP/indel base qualities stratified by SNV/indel type, useful for setting MIN_SNV_INDEL_QUAL

# initialize reporting
our $script = "index_fragments";
our $error  = "$script error";

# working variables
use vars qw($chromIndex1 @aln $varKey $snvAlnsH);

# load dependencies
my $perlUtilDir = "$ENV{MODULES_DIR}/utilities/perl";
map { require "$perlUtilDir/$_.pl" } qw(workflow);

# environment variables
fillEnvVar(\our $HAS_BASE_ACCURACY,     'HAS_BASE_ACCURACY');
fillEnvVar(\our $MIN_SNV_INDEL_QUAL,    'MIN_SNV_INDEL_QUAL');
fillEnvVar(\our $SNV_ALNS_PREFIX,       'SNV_ALNS_PREFIX');

# check the platform
!$HAS_BASE_ACCURACY and die "\nSNV/indel analysis only applies to sequencing platforms with high base accuracy\n";

# constants
use constant {
    S_QNAME             => 0, # SITE_SAM fields
    S_FLAG              => 1,
    S_RNAME             => 2,
    S_POS1              => 3,
    S_MAPQ              => 4,
    S_CIGAR             => 5,
    SITE_INDEX1_1       => 6,
    SITE_POS1_1         => 7,
    SITE_DIST_1         => 8,
    SITE_INDEX1_2       => 9,
    SITE_POS1_2         => 10,
    SITE_DIST_2         => 11,
    SEQ_SITE_INDEX1_2   => 12,
    SEQ_SITE_POS1_2     => 13,
    IS_END_TO_END_READ  => 14,
    IS_END_TO_END_INSERT=> 15,
    NODE_5              => 16,
    NODE_3              => 17,
    CH_TAG              => 18,
    TL_TAG              => 19,
    INSERT_SIZE         => 20,
    IS_ALLOWED_SIZE     => 21,
    FM_TAG              => 22,
    DE_TAG              => 23,
    HV_TAG              => 24,
    N_REF_BASES         => 25,
    N_READ_BASES        => 26,
    STEM5_LENGTH        => 27,
    STEM3_LENGTH        => 28,
    PASSED_STEM5        => 29,
    PASSED_STEM3        => 30,
    BLOCK_N             => 31,
    ALN_FAILURE_FLAG    => 32,
    JXN_FAILURE_FLAG    => 33,
    TARGET_CLASS        => 34,
    IS_ON_TARGET        => 35,
    READ_HAS_JXN        => 36,
    S_SEQ               => 37,
    S_QUAL              => 38,
    CS_TAG              => 39,
    #-------------
    S_VA_TAG            => 40,
    S_LEFT_CLIP         => 41,
    S_RIGHT_CLIP        => 42,
    S_END_POS1          => 43,
    #-------------
    FALSE  => 0,
    TRUE   => 1,
};

# create a hash key for a read and count it in the index
sub indexRead {
    join("\t",

        # fields used for sorting, dropped from the final indexed output (the va tag carries coordinates also)
        # these positions do not include clips, they are the 5'-most and 3'-most positions of the aligned portion of the read
        sprintf("%09d", $aln[S_POS1]).sprintf("%09d", $aln[S_END_POS1]), # leftPos1.rightPos1

        # fields found in the final indexed output
        $aln[S_VA_TAG],   # vaTag
        getQsTag(\@aln),  # qsTag
        $aln[S_LEFT_CLIP] # readOffset; with S_POS1 provides an identifier for the leftmost end of the read
    )
}

# reverse the process to convert counted hash keys to output formats
my $varKey_start = qr/^(\d{9})\d{9}\t(.+)/;
sub printIndexedVariant {
    my ($nObserved) = @_;
    $varKey =~ m/$varKey_start/; 
    print $snvAlnsH join("\t", # file name carries chromosome and strand information
        $1 + 0, # keep alignment leftPos1 for pileup registration
        $2,
        $nObserved
    ), "\n";
}

# do the work
require "$ENV{ACTION_DIR}/index/index_frags_runner.pl";
