// actions:
//   prepare read alignments for variant analysis, performing steps that require RE site data
//     when applicable to RE fragment libraries:
//         match alignment nodes to RE filtering sites
//         ??? discard sequences where one or both complete outer nodes fail to match an RE filtering site
//         project the 3' end of read alignments to the next RE site
//     flag chimeric junctions at SV breakpoint nodes that match:
//         - RE sites (due to intermolecular ligation, when applicable)
//     when applicable to size-selected libraries:
//         assess whether insert size/stem length is within the allowed range
//     flag reads that contain junctions that passed all alignment and junction quality filters
// input:
//   SAM stream from NAME_BAM_FILE, as generated by `align` step, on STDIN
//   FILTERING_SITES_FILE created by locate/tabulate_endpoints.R
//   config parameters:
//       ACCEPT_ENDPOINT_DISTANCE, stricter, for RE outer endpoints
//       REJECT_JUNCTION_DISTANCE, more permissive, thus rejects end-to-end chimeras more easily
//       etc.
// output:
//   modified SAM on STDOUT with custom tags added at end
//      all alignments (from all validated RE fragments) are still present
//          even those that had alignment or junction-level failure flags set to support filtering downstream
//          ??? except that inserts that don't match expected RE fragments at outer endpoints are discarded
//   write FILTERED_INSERT_SIZES_FILE=${DATA_FILE_PREFIX}.insert_sizes.filtered.txt
//   write FILTERED_STEM_LENGTHS_FILE=${DATA_FILE_PREFIX}.stem_lengths.filtered.txt

// modules
mod site_matching;
mod insert_sizes;
mod outer_nodes;

// dependencies
use std::error::Error;
use crossbeam::channel::{Sender, Receiver, bounded};
use mdi::pub_key_constants;
use mdi::workflow::{Workflow, Config, Counters};
use mdi::RecordStreamer;
use genomex::sam::{SamRecord, flag};
use genomex::genome::Chroms;
use crate::formats::hf3_tags::*;
use crate::junctions::JxnFailureFlag;
use crate::sites::{SiteMatch, SiteMatches};
use crate::inserts::ReadFailureFlag;
use insert_sizes::InsertSizer;
use outer_nodes::OuterNodes;
use site_matching::{SiteMatcher, N_SITES, N_MATCHES_BY_OUTCOME};

// Tool structure for passing data workers to record processing functions.
struct Tool {
    chroms:                      Chroms,
    site_matcher:                SiteMatcher,
    insert_sizer:                InsertSizer,
    incoming_tags:               Vec<&'static str>,
    expecting_endpoint_re_sites: bool,
    rejecting_junction_re_sites: bool,
    is_end_to_end_platform:      bool,
    is_paired_reads:             bool,
    is_ont:                      bool,
    clip_tolerance:              u32,
    accept_endpoint_distance:    u32
}

// Outcomes enum for worker threads to transmit different kind of read outcomes.
enum Outcome {
    Read(ReadOutcome),
    SiteMatch(&'static str),
    Junction(&'static str),
    InsertSize(InsertSizeOutcome),
    StemLength(StemLengthOutcome),
}
// ReadOutcome structure for collecting read outcomes and alignment counts.
struct ReadOutcome {
    pub reason: &'static str,
    pub n_alns: usize,
}
// InsertSize structure for passing insert size counts.
struct InsertSizeOutcome {
    pub read_type:     &'static str,
    pub read_type_str: Option<String>, // for custom assembled keys
    pub size_bin:      usize,
}
// StemLength structure for passing stem length counts.
struct StemLengthOutcome {
    pub read_type:     &'static str,
    pub read_type_str: Option<String>,
    pub size_bin:      usize,
}

// constants 
const TOOL: &str = "analyze_inserts";
pub_key_constants!(
    // from environment variables
    N_CPU
    SEQUENCING_PLATFORM
    IS_END_TO_END_READ
    READ_PAIR_TYPE
    EXPECTING_ENDPOINT_RE_SITES
    REJECTING_JUNCTION_RE_SITES // can be true if EXPECTING_ENDPOINT_RE_SITES is false
    CLIP_TOLERANCE // RE site matching tolerances and thresholds
    ACCEPT_ENDPOINT_DISTANCE
    // derived configuration values
    IS_END_TO_END_PLATFORM
    IS_PAIRED_READS
    IS_ONT
    // counter keys
    N_READS_IN
    N_ALNS
    N_READS_BY_OUTCOME
    N_JXNS_BY_REASON
    // read outcomes
    FAIL_UNMAPPED
    FAIL_OFF_TARGET
    FAIL_SITE_LOOKUP
    FAIL_CLIP_TOLERANCE
    FAIL_SITE_DISTANCE
    KEEP_WITH_PASSED_JXN
    KEEP_ALL_FAILED_JXNS
    KEEP_NO_JXNS
    // jxn failure keys
    JXN_FAIL_NONE
    JXN_FAIL_TRAVERSAL_DELTA // checked upstream
    JXN_FAIL_NONCANONICAL
    JXN_FAIL_FOLDBACK_INV
    JXN_FAIL_LOW_QUAL_INS
    JXN_FAIL_HAS_ADAPTER
    JXN_FAIL_SITE_MATCH // checked here
    JXN_FAIL_STEM_LENGTH
    JXN_FAIL_UPSTREAM
);
const TRIM5: usize = 0;
const TRIM3: usize = 1;
const CHANNEL_CAPACITY: usize = 1_000;

// tool function called by hf3_tools main()
pub fn stream() -> Result<(), Box<dyn Error>> {

    // get config from environment variables
    let mut cfg = Config::new();
    cfg.set_usize_env(&[N_CPU]);
    cfg.set_string_env(&[SEQUENCING_PLATFORM, READ_PAIR_TYPE]);
    cfg.set_bool_env(&[IS_END_TO_END_READ, EXPECTING_ENDPOINT_RE_SITES, REJECTING_JUNCTION_RE_SITES]);
    cfg.set_u32_env(&[CLIP_TOLERANCE, ACCEPT_ENDPOINT_DISTANCE]);

    // set derived config values
    cfg.set_bool( IS_END_TO_END_PLATFORM, *cfg.get_bool(IS_END_TO_END_READ));
    cfg.set_bool( IS_PAIRED_READS,        cfg.equals_string(READ_PAIR_TYPE, "paired"));
    cfg.set_bool( IS_ONT,                 cfg.equals_string(SEQUENCING_PLATFORM, "ONT"));

    // initialize counters
    let mut ctrs = Counters::new(TOOL, &[
        (N_READS_IN, "input reads = single reads, merged pairs, or individual unmerged reads"),
        (N_ALNS,     "input alignments"),
    ]);
    ctrs.add_keyed_counters(&[
        (N_READS_BY_OUTCOME,     "number of reads by outcome"),
        (N_JXNS_BY_REASON,       "junction failure counts by reason (non-exclusive)"),
    ]);

    // initialize the tool
    let mut w = Workflow::new(TOOL, cfg, ctrs);
    w.log.initializing();

    // build tool support resources, i.e. data workers
    let (insert_sizer, insert_size_counts, stem_length_counts) = 
        InsertSizer::new(&mut w); 
    let tool = Tool {
        chroms:                       Chroms::new(&mut w.cfg),
        insert_sizer:                 insert_sizer,
        site_matcher:                 SiteMatcher::new(&mut w),
        incoming_tags:                StageTags::AlignmentAnalysis.tags_after_stage(),
        expecting_endpoint_re_sites: *w.cfg.get_bool(EXPECTING_ENDPOINT_RE_SITES),
        rejecting_junction_re_sites: *w.cfg.get_bool(REJECTING_JUNCTION_RE_SITES),
        is_end_to_end_platform:      *w.cfg.get_bool(IS_END_TO_END_PLATFORM),
        is_ont:                      *w.cfg.get_bool(IS_ONT),
        is_paired_reads:             *w.cfg.get_bool(IS_PAIRED_READS),
        clip_tolerance:              *w.cfg.get_u32(CLIP_TOLERANCE),
        accept_endpoint_distance:    *w.cfg.get_u32(ACCEPT_ENDPOINT_DISTANCE)
    };

    // process records in parallel threads
    let (tx_outcome, rx_outcome) = 
        bounded::<Outcome>(CHANNEL_CAPACITY);
    let n_workers = (*w.cfg.get_usize(N_CPU)).max(3) - 2; // leave one thread for streamer and outcome collector
    w.log.print("matching alignments to RE sites and analyzing insert sizes");
    crossbeam::scope(|scope| {

        // collect and increment outcome counters in a separate thread
        scope.spawn(move |_| {
            count_events(
                rx_outcome,
                w,
                insert_size_counts,
                stem_length_counts,
                tool.site_matcher.is_matching_sites,
                tool.insert_sizer.size_plot_bin_size,
            );
        });

        // process groups of SAM records for each read in a stream (blocks main thread until finished)
        RecordStreamer::new()
            .comment(b'@')
            .no_trim()
            .flexible()
            .group_by_in_place_parallel(
                |alns: &mut [SamRecord]| record_parser(
                    alns, 
                    &tx_outcome,
                    &tool,
                ), 
                &["qname"], // suffixed by /1 or /2 for unmerged paired reads
                n_workers, // leave one thread for outcome collector
                CHANNEL_CAPACITY,
            );
        drop(tx_outcome);
    }).unwrap();
    Ok(())
}

// process all alignments for one read (paired reads are handled separately)
fn record_parser(
    alns:       &mut [SamRecord], 
    tx_outcome: &Sender<Outcome>,
    tool:       &Tool,
) -> Result<Vec<usize>, Box<dyn Error + Send + Sync>> {
    let n_alns = alns.len();

    // reset tags in case this is a re-application of analyze_inserts to NAME_BAM_FILE
    alns.iter_mut().for_each(|aln| aln.tags.retain(&tool.incoming_tags));

    // stop processing unmapped reads
    if alns[0].check_flag_any(flag::UNMAPPED) { 
        return failed_read(alns, tx_outcome, FAIL_UNMAPPED, ReadFailureFlag::Unmapped as u8);
    }

    // stop processing off-target reads, they will never call variants
    if alns[0].get_tag_value(READ_IS_OFF_TARGET).is_some() { 
        return failed_read(alns, tx_outcome, FAIL_OFF_TARGET, ReadFailureFlag::OffTarget as u8);
    }

    // determine if this is an unmerged read pair
    let paired_outer_node = if tool.is_paired_reads {
        alns[0].get_tag_value_parsed::<isize>(PAIRED_OUTER_NODE)
    } else {
        None
    };
    let is_unmerged_pair = paired_outer_node.is_some();

    // collect read outer adapter trims (0,0 for all except ONT trimmed reads)
    let trims = if let Some(tl_tag) = alns[0].get_tag_value(TRIM_LENGTHS) {
        tl_tag.split(',').map(|x| x.parse::<usize>().unwrap()).collect::<Vec<_>>()
    } else {
        vec![0, 0]
    };

    // check the ends of all alignments for RE site matches, when applicable
    // adjust outer site positions for clips
    // stop processing sequences, i.e., single/merged reads or read pairs as suspect if a required outer endpoint:
    //  - outer clip is more than CLIP_TOLERANCE bp in length
    //  - clip-adjusted endpoint position is more than ACCEPT_ENDPOINT_DISTANCE bp away from closest RE site
    //        *       *       *     proper sitePos1 values
    //   ----|5-----3/5-----3|----  as nodes are numbered for alignments
    //   ----|3-----5/3-----5|----
    let mut is_end_to_end_read = false;
    let mut aln_sites: Vec<SiteMatches> = Vec::with_capacity(n_alns);
    for i in 0..n_alns {
        let (site5, site3) = tool.site_matcher.match_aln_sites(tx_outcome, &alns[i]);
        // we expect the RE site lookup to succeed even if the ends don't match RE sites
        // don't process reads further if any end of any alignment fails to match an RE site
        if tool.rejecting_junction_re_sites && 
           (site5.index1 == 0 || site3.index1 == 0) {
            return failed_read(alns, tx_outcome, FAIL_SITE_LOOKUP, ReadFailureFlag::SiteLookup as u8);
        }
        if i == 0 { // read 5' end
            // perform initial end-to-end status determination
            is_end_to_end_read = 
                 tool.is_end_to_end_platform || 
                (tool.is_ont && trims[TRIM3] > 0) || 
                (tool.is_paired_reads && !is_unmerged_pair);
            // check 5' query end, always required to match a RE site if ligFree
            let is_reverse = alns[i].check_flag_any(flag::REVERSE);
            let clip5 = if tool.is_ont && trims[TRIM5] == 0 {
                0 // when ONT untrimmed, clip would include the adapter...
            } else if is_reverse {
                alns[i].get_clip_right()
            } else {
                alns[i].get_clip_left()
            };
            if clip5 > tool.clip_tolerance {
                return failed_read(alns, tx_outcome, FAIL_CLIP_TOLERANCE, ReadFailureFlag::ClipTolerance as u8);
            }
            if tool.expecting_endpoint_re_sites {
                let dist5 = if is_reverse {
                    site5.distance + clip5 as i32
                } else {
                    site5.distance - clip5 as i32
                };
                if dist5.abs() as u32 > tool.accept_endpoint_distance {
                    return failed_read(alns, tx_outcome, FAIL_SITE_DISTANCE, ReadFailureFlag::SiteDistance as u8);
                }
            }
        }
        if i == n_alns - 1 { // read 3' end
            // 3' query end if an end-to-end sequence
            // 3' ends on incomplete platforms/sequences are not _required_ to match an RE, but they may be found to do so below
            let is_reverse = alns[i].check_flag_any(flag::REVERSE);
            let clip3 = if tool.is_ont && trims[TRIM3] == 0 {
                0 // when ONT untrimmed, clip might include the adapter...
            } else if is_reverse {
                alns[i].get_clip_left()
            } else {
                alns[i].get_clip_right()
            };
            let dist3 = if is_reverse {
                site3.distance - clip3 as i32
            } else {
                site3.distance + clip3 as i32
            };
            if is_end_to_end_read {
                if clip3 > tool.clip_tolerance {
                    return failed_read(alns, tx_outcome, FAIL_CLIP_TOLERANCE, ReadFailureFlag::ClipTolerance as u8);
                }
                if tool.expecting_endpoint_re_sites && dist3.abs() as u32 > tool.accept_endpoint_distance {
                    return failed_read(alns, tx_outcome, FAIL_SITE_DISTANCE, ReadFailureFlag::SiteDistance as u8);
                }
            // promote incomplete sequences to end-to-end status if they got to the fragment end
            } else if tool.expecting_endpoint_re_sites && 
                      !is_unmerged_pair && 
                      dist3.abs() as u32 <= tool.accept_endpoint_distance {
                is_end_to_end_read = true;
            }
        }
        aln_sites.push(SiteMatches{site5, site3, proj3: SiteMatch::new()});
    }
    let is_end_to_end_insert = is_end_to_end_read || tool.is_paired_reads;

    // collect initial 3' site projections when we already know them from end-to-end, non-SV reads
    let read_has_jxn = n_alns > 1;
    if is_end_to_end_read && !read_has_jxn {
        aln_sites[0].proj3 = aln_sites[0].site3.clone();
        aln_sites[0].proj3.index1 = aln_sites[0].proj3.index1.abs();
        aln_sites[0].proj3.distance = 0;
    }

    // collect outermost nodes for deduplication downstream
    // this process continues making RE site projections as needed
    let outer_nodes = OuterNodes::get_outer_nodes(
        alns,
        &mut aln_sites,
        is_unmerged_pair,
        paired_outer_node,
        tool,
        tx_outcome,
    );

    // assess the insert sizes and stem lengths of all alignments
    let insert_sizes = tool.insert_sizer.assess_insert_sizes(
        alns,
        is_unmerged_pair,
        paired_outer_node,
        &trims,
        is_end_to_end_read,
        &tool.chroms,
    );

    // collect the distributions of insert sizes of on-target reads
    let reason: &'static str;
    let read_has_passed_jxn = if read_has_jxn {
        let mut any_jxn_passed = false;
        let mut jxn_failure_flag: u8 = 0;
        for aln3_i in 1..n_alns {
            let aln5_i = aln3_i - 1;
            jxn_failure_flag = alns[aln5_i].get_tag_value_parsed::<u8>(JXN_FAILURE_FLAG_INIT).unwrap_or(0);
            if jxn_failure_flag != 0 {
                tx_outcome.send(Outcome::Junction(JXN_FAIL_UPSTREAM))?;
            }
            jxn_failure_flag |= tool.site_matcher.check_jxn(tx_outcome, &aln_sites,    aln5_i, aln3_i) as u8;
            jxn_failure_flag |= tool.insert_sizer.check_jxn(tx_outcome, &insert_sizes, aln5_i, aln3_i) as u8;
            if jxn_failure_flag != JxnFailureFlag::None as u8 {
                alns[aln5_i].set_tag_value(JXN_FAILURE_FLAG, &jxn_failure_flag);
            }
            any_jxn_passed = any_jxn_passed || jxn_failure_flag == 0;
        }
        tool.insert_sizer.record_sv_sizes(tx_outcome, &insert_sizes, &alns, jxn_failure_flag, &tool.chroms).unwrap();
        if any_jxn_passed {
            reason = KEEP_WITH_PASSED_JXN;
        } else {
            reason = KEEP_ALL_FAILED_JXNS;
        }
        any_jxn_passed
    } else {
        tool.insert_sizer.record_non_sv_sizes(tx_outcome, &insert_sizes, &aln_sites).unwrap();
        reason = KEEP_NO_JXNS;
        false
    };

    // read and insert-level properties repeat the same on all alignments
    let end_to_end_tag = ((is_end_to_end_insert as u8) << 1) | (is_end_to_end_read as u8);
    let outer_nodes = outer_nodes.to_sam_tag();
    for i in 0..n_alns {
        alns[i].set_tag_value(IS_END_TO_END, &end_to_end_tag);
        alns[i].set_tag_value(OUTER_NODES,   &outer_nodes);
        if tool.site_matcher.is_matching_sites {
            alns[i].set_tag_value(CLOSEST_SITES, &aln_sites[i].to_tag());
        }
        if tool.insert_sizer.is_size_selected {
            alns[i].set_tag_value(INSERT_SIZE,   &insert_sizes.insert_size);
            alns[i].set_tag_value(STEM_LENGTH5,  &insert_sizes.stem_lengths[i].stem5);
            alns[i].set_tag_value(STEM_LENGTH3,  &insert_sizes.stem_lengths[i].stem3);
        }
        if read_has_passed_jxn {
            alns[i].set_tag_value(READ_HAS_PASSED_JXN, &1);
        }
    }

    // print all alignments for the read, regardless of outcome
    tx_outcome.send(Outcome::Read(ReadOutcome{
        reason,
        n_alns,
    }))?;
    Ok((0..n_alns).collect())
}

// short-circuit a failed read
fn failed_read(
    alns:   &mut [SamRecord],
    tx_outcome: &Sender<Outcome>,
    reason: &'static str,
    flag:   u8,
) -> Result<Vec<usize>, Box<dyn Error + Send + Sync>> {
    let n_alns = alns.len();
    for i in 0..n_alns {
        alns[i].set_tag_value(READ_FAILURE_FLAG, &flag);
    }
    tx_outcome.send(Outcome::Read(ReadOutcome{
        reason,
        n_alns,
    }))?;
    Ok((0..n_alns).collect()) 
}

// thread for aggregating and reporting read metadata
fn count_events(
    rx_outcome:             Receiver<Outcome>,
    mut w:                  Workflow,
    mut insert_size_counts: Counters,
    mut stem_length_counts: Counters,
    is_matching_sites:      bool,
    size_plot_bin_size:     f64,
){
    // aggregate outcomes while threads are processing records
    for outcome in rx_outcome {
        match outcome {
            Outcome::Read(read_outcome) => {
                w.ctrs.increment(N_READS_IN);
                w.ctrs.add_to(N_ALNS, read_outcome.n_alns);
                w.ctrs.increment_keyed(N_READS_BY_OUTCOME, read_outcome.reason);
            },
            Outcome::SiteMatch(reason) => {
                w.ctrs.increment_keyed(N_MATCHES_BY_OUTCOME, reason);
            },
            Outcome::Junction(reason) => {
                w.ctrs.increment_keyed(N_JXNS_BY_REASON, reason);
            },
            Outcome::InsertSize(insert_size) => {
                if let Some(ref read_type) = insert_size.read_type_str {
                    insert_size_counts.increment_indexed(read_type, insert_size.size_bin);
                } else { 
                    insert_size_counts.increment_indexed(insert_size.read_type, insert_size.size_bin);
                }
            },
            Outcome::StemLength(stem_length) => {
                if let Some(ref read_type) = stem_length.read_type_str {
                    stem_length_counts.increment_indexed(read_type, stem_length.size_bin);
                } else { 
                    stem_length_counts.increment_indexed(stem_length.read_type, stem_length.size_bin);
                }
            },
        }
    }

    // print insert sizes and stem lengths summary for plotting
    InsertSizer::print_insert_sizes(
        &mut w.cfg, 
        insert_size_counts, 
        stem_length_counts, 
        size_plot_bin_size
    );

    // report counter values
    let null_ctr: Vec<&str> = vec![];
    w.ctrs.print_grouped(&[
        if is_matching_sites { &[N_SITES] } else { &null_ctr },
        &[N_READS_IN, N_ALNS],
        &[N_READS_BY_OUTCOME],
        if is_matching_sites { &[N_MATCHES_BY_OUTCOME] } else { &null_ctr },
        &[N_JXNS_BY_REASON],
    ]);
}
