// actions:
//   prepare read alignments for variant analysis, performing steps that require RE site data
//     when applicable to RE fragment libraries:
//         match alignment nodes to RE filtering sites
//         ??? discard sequences where one or both complete outer nodes fail to match an RE filtering site
//         project the 3' end of read alignments to the next RE site
//     flag chimeric junctions at SV breakpoint nodes that match:
//         - RE sites (due to intermolecular ligation, when applicable)
//     when applicable to size-selected libraries:
//         assess whether insert size/stem length is within the allowed range
//     flag reads that contain junctions that passed all alignment and junction quality filters
// input:
//   SAM stream from NAME_BAM_FILE, as generated by `align` step, on STDIN
//   FILTERING_SITES_FILE created by locate/tabulate_endpoints.R
//   config parameters:
//       ACCEPT_ENDPOINT_DISTANCE, stricter, for RE outer endpoints
//       REJECT_JUNCTION_DISTANCE, more permissive, thus rejects end-to-end chimeras more easily
//       etc.
// output:
//   modified SAM on STDOUT with custom tags added at end
//      all alignments (from all validated RE fragments) are still present
//          even those that had alignment or junction-level failure flags set to support filtering downstream
//          ??? except that inserts that don't match expected RE fragments at outer endpoints are discarded
//   write FILTERED_INSERT_SIZES_FILE=${DATA_FILE_PREFIX}.insert_sizes.filtered.txt
//   write FILTERED_STEM_LENGTHS_FILE=${DATA_FILE_PREFIX}.stem_lengths.filtered.txt

// modules
mod site_matching;
mod insert_sizes;

// dependencies
use std::error::Error;
use mdi::pub_key_constants;
use mdi::workflow::{Workflow, Config, Counters, COUNTER_SEPARATOR};
use mdi::RecordStreamer;
use genomex::sam::{SamRecord, flag};
use genomex::genome::Chroms;
use crate::formats::hf_tags::*;
use insert_sizes::InsertSizer;
use site_matching::SiteMatcher;

// Tool structure, for passing data workers to record processing functions.
struct Tool {
    chroms: Chroms,
    site_matcher: SiteMatcher,
    insert_sizer: InsertSizer,
    incoming_tags: Vec<&'static str>,
    stage_tags:    Vec<&'static str>,
}

// constants 
const TOOL: &str = "analyze_inserts";
pub_key_constants!(
    // from environment variables
    SEQUENCING_PLATFORM
    IS_END_TO_END_READ
    READ_PAIR_TYPE
    REJECTING_JUNCTION_RE_SITES
    READ_LENGTH_TYPE
    // derived configuration values
    IS_END_TO_END_PLATFORM
    IS_PAIRED_READS
    IS_ONT
    SIZE_PLOT_BIN_SIZE

    // IS_END_TO_END_PLATFORM
    // IS_PAIRED_READS
    // IS_ONT
    // IS_SIZE_SELECTED
    // MAX_ALLOWED_SIZE
    // SIZE_PLOT_BIN_SIZE

    // counter keys
    N_SEQS
    N_READS
    N_ALNS
    N_JXNS_REJECTED

    // N_ALNS
    // N_EVENTS
    // N_READS_OUT
    // N_READS_SV
    // N_JXNS
    // N_BLOCKS
    // N_BAD_TRAVERSAL

    N_DISCARDED
    N_BY_READ_OUTCOME
);

    // // read outcomes
    // KEPT_SEQUENCE 
    // NONCANONICAL_CHROM 
    // FAILED_SITE_LOOKUP
    // TELOMERIC_FRAGMENT 
    // CLIP_TOO_LARGE 
    // DISTANCE_TOO_LARGE
    // UNTRIMMED_ONT_ADAPTER
    // IS_OFF_TARGET 

    // discard reasons
    // KEPT_SEQUENCE           => "valid on-target reads passed to fragment analysis",
    // NONCANONICAL_CHROM      => "reads had their 5' alignment on a non-canonical chromosome",
    // FAILED_SITE_LOOKUP      => "reads failed site lookup",
    // TELOMERIC_FRAGMENT      => "reads were telomeric fragments",
    // CLIP_TOO_LARGE          => "reads had a clip that was too large",
    // DISTANCE_TOO_LARGE      => "reads had an outer site distance that was too large",
    // UNTRIMMED_ONT_ADAPTER   => "ONT reads lacked a 5' adapter trim",
    // IS_OFF_TARGET           => "reads had 5' (ONT) or all (other platforms) off-target alignment(s)",

    // read junction statuses
const HAS_PASSED_JXN: &str  = "at least one passed junction";
const ALL_FAILED_JXNS: &str = "all failed junctions";
const HAS_NO_JXNS: &str     = "no junctions";
// read length types
const READ_LEN_PROPER: &str       = "nonSV.actual";
const PROJ_LEN_PROPER: &str       = "nonSV.projected";
const READ_LEN_CHIMERIC: &str     = "SV.chimeric"; // cannot assess projected size of structural variant reads
const READ_LEN_NON_CHIMERIC: &str = "SV.passed";   // these include all SV reads, not just translocations


// tool function called by hf3_tools main()
pub fn stream() -> Result<(), Box<dyn Error>> {

    // get config from environment variables
    let mut cfg = Config::new();
    cfg.set_string_env(&[SEQUENCING_PLATFORM, READ_PAIR_TYPE]);
    cfg.set_bool_env(&[IS_END_TO_END_READ, REJECTING_JUNCTION_RE_SITES]);

    // set derived config values
    cfg.set_bool( IS_END_TO_END_PLATFORM, *cfg.get_bool(IS_END_TO_END_READ));
    cfg.set_bool( IS_PAIRED_READS,        cfg.equals_string(READ_PAIR_TYPE, "paired"));
    cfg.set_bool( IS_ONT,                 cfg.equals_string(SEQUENCING_PLATFORM, "ONT"));
    cfg.set_usize(SIZE_PLOT_BIN_SIZE, if cfg.equals_string(READ_LENGTH_TYPE, "short") { 10 } else { 250 });

    // initialize counters
    let mut ctrs = Counters::new(TOOL, &[
        (N_SEQS,      "sequences, i.e., single reads or read pairs"),
        (N_READS,     "reads"),
        (N_ALNS,      "alignments"),
    ]);
    ctrs.add_keyed_counters(&[
        // (N_BY_GENOME, "reads by genome"),
        (N_JXNS_REJECTED, "junction failure counts by reason")
    ]);

    // // initialize counters
    // let mut ctrs = Counters::new(TOOL, vec![
    //     (COUNTER_SEPARATOR, "")
    //     (N_ALNS,            "input alignments"),
    //     (N_EVENTS,          "input events (single-end reads or read pairs)"),
    //     (N_READS_OUT,       "output reads (after splitting unmerged read pairs"),
    //     (COUNTER_SEPARATOR, "")

    //     (N_READS_SV,        "analyzed reads with >1 alignment"),
    //     (N_JXNS,            "junctions in analyzed SV reads)"),
    // ]);


    // initialize the tool
    let mut w = Workflow::new(TOOL, cfg, ctrs);
    w.log.print("initializing");

    // build tool support resources, i.e. data workers
    let mut tool = Tool {
        chroms: Chroms::new(&mut w.cfg),
        site_matcher: SiteMatcher::new(&mut w),
        insert_sizer: InsertSizer::new(&mut w),
        incoming_tags: StageTags::AlignmentAnalysis.tags_after_stage(),
        stage_tags:    StageTags::InsertAnalysis.tag_added_by_stage(),
    };

    // process groups of SAM records for each read in a stream
    w.log.print("matching alignments to RE sites and analyzing insert sizes");
    let mut rs = RecordStreamer::new();
    rs
        .comment(b'@')
        .no_trim()
        .flexible()
        .group_by_in_place_serial(|alns: &mut Vec<SamRecord>| record_parser(
            alns, 
            &mut w,
            &mut tool,
        ), &["qname"]); // suffixed by /1 or /2 for unmerged paired reads

    // report counter values
    w.ctrs.print_all();
    Ok(())
}

// process all alignments for one read (paired reads are handled separately)
fn record_parser(
    alns: &mut Vec<SamRecord>, 
    w: &mut Workflow,
    tool: &mut Tool,
) -> Result<Vec<usize>, Box<dyn Error>> {
    w.ctrs.increment(N_SEQS);

//     # check the ends of all alignments for RE site matches
//     # discard sequences if outer ends do not match within tolerance
//     # adjust outer site positions for clips
//     # reject sequences if, for a required outer endpoint:
//     #   outer clip is more than CLIP_TOLERANCE bp in length
//     #   clip-adjusted endpoint position is more than ACCEPT_ENDPOINT_DISTANCE bp away from closest RE site
//     #        *       *       *     proper sitePos1 values
//     #   ----|5-----3/5-----3|----  as nodes are numbered for alignments
//     #   ----|3-----5/3-----5|----
//     my ($isEndToEndRead, @trims);
//     my $tl = $alns[0][SAM_TAGS] =~ m/\ttl:Z:(\S+)/ ? $1 : "0,0";
//     foreach my $i(0..$#alns){
//         if($alns[$i][S_FLAG] & _REVERSE){ # outer endpoints are site matched even when EXPECTING_ENDPOINT_RE_SITES is FALSE if REJECTING_JUNCTION_RE_SITES is TRUE
//             @{$alns[$i]}[SITE_INDEX1_1..SITE_DIST_2] = $REJECTING_JUNCTION_RE_SITES ? (
//                 findClosestSite($alns[$i][S_RNAME], getEnd($alns[$i][S_POS1], $alns[$i][S_CIGAR]) + 1 - $correction5),
//                 findClosestSite($alns[$i][S_RNAME], $alns[$i][S_POS1] - $correction5)
//             ) : @nullSites;
//         } else {
//             @{$alns[$i]}[SITE_INDEX1_1..SITE_DIST_2] = $REJECTING_JUNCTION_RE_SITES ? ( 
//                 findClosestSite($alns[$i][S_RNAME], $alns[$i][S_POS1]),
//                 findClosestSite($alns[$i][S_RNAME], getEnd($alns[$i][S_POS1], $alns[$i][S_CIGAR]) + 1)
//             ) : @nullSites;
//         }
//         if($i == 0){ # read 5' end
//             if($REJECTING_JUNCTION_RE_SITES){
//                 $alns[$i][SITE_INDEX1_1] or return FAILED_SITE_LOOKUP;

//                 # reject telomeric fragments, i.e., that would cross past the first or last RE site on chrom
//                 if($alns[$i][S_FLAG] & _REVERSE){
//                     abs($alns[$i][SITE_INDEX1_1]) >  1 or return TELOMERIC_FRAGMENT;
//                 } else {
//                     abs($alns[$i][SITE_INDEX1_1]) <  ${$chromData{$alns[$i][S_RNAME]}}[nSites_] or return TELOMERIC_FRAGMENT;
//                 }
//             }

//             # get ONT adapter trims once per read
//             @trims = split(",", $tl);

//             # perform initial end-to-end status determination
//             $isEndToEndRead = (
//                 $isEndToEndPlatform or 
//                 ($isONT and $trims[TRIM3]) or # TODO: also check from 3' adapter trim on Aviti_1x300 and Ultima, i.e., add tl tag to those platforms
//                 ($isPairedReadPlatform and !$isUnmergedPair)
//             ) ? TRUE : FALSE;
//             # check 5' query end, always required to match a RE site
//             my $clip5 = 
//                 ($isONT and !$trims[TRIM5]) ?
//                 0 : # when ONT untrimmed, clip would include the adapter...
//                 (($alns[$i][S_FLAG] & _REVERSE) ? getRightClip($alns[$i][S_CIGAR]) : getLeftClip($alns[$i][S_CIGAR]));
//             $clip5 > $CLIP_TOLERANCE and return CLIP_TOO_LARGE;
//             if($EXPECTING_ENDPOINT_RE_SITES){
//                 my $dist5 = abs( ($alns[$i][S_FLAG] & _REVERSE) ? $alns[$i][SITE_DIST_1] + $clip5 : $alns[$i][SITE_DIST_1] - $clip5 );
//                 $dist5 > $ACCEPT_ENDPOINT_DISTANCE and return DISTANCE_TOO_LARGE;
//             }
//         }
//         if($i == $#alns){ # read 3' end
//             !$REJECTING_JUNCTION_RE_SITES or $alns[$i][SITE_INDEX1_2] or return FAILED_SITE_LOOKUP;

//             # aln3 is guaranteed by 'locate' to be between 1 and nSitesChrom

//             # 3' query end if an end-to-end sequence
//             # 3' ends on incomplete platforms/sequences are not _required_ to match an RE, but they may be found to do so below
//             my $clip3 = 
//                 ($isONT and !$trims[TRIM3]) ?
//                 0 :
//                 (($alns[$i][S_FLAG] & _REVERSE) ? getLeftClip($alns[$i][S_CIGAR]) : getRightClip($alns[$i][S_CIGAR]));
//             my $dist3 = abs( ($alns[$i][S_FLAG] & _REVERSE) ? $alns[$i][SITE_DIST_2] - $clip3 : $alns[$i][SITE_DIST_2] + $clip3 );
//             if($isEndToEndRead){
//                 $clip3 > $CLIP_TOLERANCE and return CLIP_TOO_LARGE;
//                 $EXPECTING_ENDPOINT_RE_SITES and $dist3 > $ACCEPT_ENDPOINT_DISTANCE and return DISTANCE_TOO_LARGE;
//             }

//             # promote incomplete sequences to end-to-end status if they got to the fragment end
//             $EXPECTING_ENDPOINT_RE_SITES and $dist3 <= $ACCEPT_ENDPOINT_DISTANCE and !$isUnmergedPair and $isEndToEndRead = TRUE;
//         }
//     }
//     my $inEndToEndInsert = ($isEndToEndRead or $isPairedReadPlatform) ? TRUE : FALSE;

//     # collect initial 3' site projections of each alignment
//     my $readHasJxn = @alns > 1 ? TRUE : FALSE;
//     foreach my $aln(@alns){
//         @$aln[SEQ_SITE_INDEX1_2..SEQ_SITE_POS1_2] = ($isEndToEndRead and !$readHasJxn) ?
//             @{$alns[-1]}[SITE_INDEX1_2..SITE_POS1_2] :
//             (0,0);
//         $$aln[SEQ_SITE_INDEX1_2] = abs($$aln[SEQ_SITE_INDEX1_2]);
//     }

//     # determine if the 5'-most alignment still needs to be projected
//     my ($node5, $node3);
//     if($EXPECTING_ENDPOINT_RE_SITES){
//         $alns[ 0][SEQ_SITE_INDEX1_2] or @{$alns[ 0]}[SEQ_SITE_INDEX1_2..SEQ_SITE_POS1_2] = getProjection($alns[0]);

//         # determine if the 3'-most alignment still needs to be projected
//         # here projection is more limited and simply bumps to the next RE site on any haplotype
//         $alns[-1][SEQ_SITE_INDEX1_2] or @{$alns[-1]}[SEQ_SITE_INDEX1_2..SEQ_SITE_POS1_2] = getProjection($alns[-1]);

//         # get outer nodes based on RE site positions
//         my $pairedSitePos1;
//         if($pairedAln5){
//             $pairedSitePos1 = (findClosestSite( # may not have assigned site position to other read yet for first read of unmerged pair
//                 $$pairedAln5[S_RNAME], 
//                 ($$pairedAln5[S_FLAG] & _REVERSE) ? getEnd($$pairedAln5[S_POS1], $$pairedAln5[S_CIGAR]) : $$pairedAln5[S_POS1],
//             ))[1] or return FAILED_SITE_LOOKUP;
//         }
//         $node5 = parseSignedNode( # reads always define their own 5' outer node
//             $alns[0], 
//             $alns[0][SITE_POS1_1], # using site positions enables fuzzy endpoint matching when comparing reads
//             BOTTOM_STRAND, TOP_STRAND
//         );
//         $node3 = $pairedAln5 ? 
//             parseSignedNode(
//                 $pairedAln5, 
//                 $pairedSitePos1,
//                 TOP_STRAND, BOTTOM_STRAND # invert the strand orientation of paired 5' ends to match the behavior of single or merged reads
//             ) : 
//             parseSignedNode(
//                 $alns[-1], 
//                 $alns[-1][SEQ_SITE_POS1_2],  # using projected 3' ends allows best deduplication of partially sequenced RE fragments
//                 BOTTOM_STRAND, TOP_STRAND
//             );

//     # get outer nodes based on alignment positions
//     } else {
//         $node5 =  parseSignedNode(
//             $alns[0], 
//             ($alns[0][S_FLAG] & _REVERSE) ? getEnd($alns[0][S_POS1], $alns[0][S_CIGAR]) : $alns[0][S_POS1], 
//             BOTTOM_STRAND, TOP_STRAND
//         );
//         $node3 = $pairedAln5 ? 
//             parseSignedNode(
//                 $pairedAln5, 
//                 ($$pairedAln5[S_FLAG] & _REVERSE) ? getEnd($$pairedAln5[S_POS1], $$pairedAln5[S_CIGAR]) : $$pairedAln5[S_POS1],
//                 TOP_STRAND, BOTTOM_STRAND
//             ) : 
//             parseSignedNode( # this unprojectable non-RE node position may not be the end of the insert if a single read is not end-to-end
//                 $alns[-1], 
//                 ($alns[-1][S_FLAG] & _REVERSE) ? $alns[-1][S_POS1] : getEnd($alns[-1][S_POS1], $alns[-1][S_CIGAR]), 
//                 BOTTOM_STRAND, TOP_STRAND
//             )
//     }

//     # collect next chunk of read-level metadata for passing into each alignment
//     my $ch = $alns[0][SAM_TAGS] =~ m/\tch:i:(\d+)/ ? $1 : 0;
//     my $readLen = length($alns[0][S_SEQ]);
//     my $insertSize = $isUnmergedPair ? -$node3 - $node5 : $readLen;
//     $isUnmergedPair and (
//         $eventHasJxn or 
//         $insertSize < 0 or
//         $insertSize > $PLATFORM_MAX_INSERT_SIZE or 
//         $alns[0][S_RNAME] ne $$pairedAln5[S_RNAME]
//     ) and $insertSize = 0; # when read carries any type of SV, whether sequenced or not, we cannot infer the true insert size
//     my $readStart0 = getQueryStart0($alns[ 0][S_FLAG], $alns[ 0][S_CIGAR]);
//     my $readEnd1   = getQueryEnd1(  $alns[-1][S_FLAG], $alns[-1][S_CIGAR], $readLen); # may not be the end of the insert
//     my $isAllowedSize = (!$isSizeSelected or ($insertSize >= $minAllowedSize and $insertSize <= $maxAllowedSize)) ? TRUE : FALSE;
//     foreach my $aln(@alns){
//         @$aln[IS_END_TO_END_READ..IS_ALLOWED_SIZE] = (
//             $isEndToEndRead, 
//             $inEndToEndInsert,
//             $node5, # like other read and insert-level properties, these repeat the same on all alignments
//             $node3, 
//             $ch, 
//             $tl, 
//             $insertSize, 
//             $isAllowedSize
//         );
//     }


//     # collect the distributions of insert sizes of on-target reads
//     my $sizeBin = int($insertSize / $sizePlotBinSize) * $sizePlotBinSize;
//     if($readHasJxn){ # disregard multi-junction reads when assessing insert sizes
//         @alns == 2 and $sizeBin and recordVariantSizes($sizeBin, @alns); 
//         $readOutcomes{$anyJxnPassed ? $hasPassedJxn : $allFailedJxns}++;
//     } else {
//         $sizeBin and $insertSizeCounts{$READ_LEN_PROPER}{$sizeBin}++;
//         my $projLen = $EXPECTING_ENDPOINT_RE_SITES ? 
//             abs($alns[0][SEQ_SITE_POS1_2] - $alns[0][SITE_POS1_1]) + 1 :
//             $insertSize;
//         $projLen and $insertSizeCounts{$PROJ_LEN_PROPER}{int($projLen / $sizePlotBinSize) * $sizePlotBinSize}++;
//         $readOutcomes{$hasNoJxns}++;
//     }

    // return the value appropriate for the streamer to indicate which records to print to STDOUT
    Ok((0..alns.len()).collect())
}
