// actions:
//   prepare read alignments for downstream variant analysis
//     purge unmapped reads
//     split unmerged read pairs for downstream processing as single-end reads
//     order alignments across each read from 5' to 3'
//     repack SAM to SITE_SAM for streamlined parsing
//     when applicable to RE fragment libraries:
//         match alignment nodes to RE filtering sites, record in SITE_INDEX1_1 to SITE_DIST_2
//         discard sequences where one or both complete outer nodes fail to match an RE filtering site
//         project the 3' end of read alignments to the next RE site, record in SEQ_SITE_INDEX1_2 to IS_END_TO_END
//     when applicable to size-selected libraries:
//         assess whether insert size/stem length is within the allowed range, record in INSERT_SIZE to PASSED_STEM3
//     calculate the traversal delta over all sets of read alignments (across all sets of junctions) to set BLOCK_N
//         used to suppress spurious junctions arising in low quality regions with ~equal inserted and deleted bases
//     enforce alignment-level quality filtering to set ALN_FAILURE_FLAG
//         used to suppress untrusted junctions arising from aligner issues
//     flag chimeric junctions, in JXN_FAILURE_FLAG, at SV breakpoint nodes that match (discard distal/3' portion):
//         - RE sites (due to intermolecular ligation, when applicable)
//         - foldback inversions (due to ONT duplex reads or inversion synthesis)
//         - low quality insertions (ONT only, to suppress follow-on chimeras)
//         - adapter insertions (due to any process that conjoins reads across an adapter)
//     when applicable to targeted libraries:
//         assess whether alignment/read ends matched a target region, record in TARGET_MATCH_FLAG
//     flag reads that contain junctions that passed and junction quality filters to set READ_HAS_JXN
// input:
//   headerless SAM from NAME_BAM_FILE, as generated by `align` step, on STDIN
//   CLOSEST_SITE_BINARY_FILE and others created by 'locate' step
//   config parameters:
//       ACCEPT_ENDPOINT_DISTANCE, stricter, for RE outer endpoints
//       REJECT_JUNCTION_DISTANCE, more permissive, thus rejects end-to-end chimeras more easily
//       etc.
// output:
//   SITE_SAM written to chromosome-level files in SITE_SAM_DIR, where:
//      each row is one alignment, like SAM
//      each read's alignments are in query order from 5' to 3'
//      unmerged paired reads are suffixed with /1 or /2 in QNAME for independent processing downstream
//      error correction fields are set as above
//      all alignments (from all validated RE fragments) are still present
//          even those that had alignment or junction-level failure flags set to support filtering downstream
//          except that inserts that don't match expected RE fragments at outer endpoints are discarded

// dependencies
use std::error::Error;
// use std::collections::HashMap;
use mdi::pub_key_constants;
use mdi::workflow::{Workflow, Config, Counters, COUNTER_SEPARATOR};
use mdi::RecordStreamer;
use genomex::sam::{SamRecord, flag};
use genomex::genome::Chroms;

// modules
mod match_nodes_to_sites;
// mod check_traversal_delta;
// mod enforce_quality_filters;
// mod split_chimeric_reads;

// constants
const TOOL: &str = "apply_filters";
pub_key_constants!(
    // from environment variables
    // genome
    GENOME_SIZE
    IS_COMPOSITE_GENOME
    // platform and library properties
    SEQUENCING_PLATFORM
    PLATFORM_MAX_INSERT_SIZE
    IS_END_TO_END_READ
    READ_PAIR_TYPE
    READ_LENGTH_TYPE
    MIN_SELECTED_SIZE
    SELECTED_SIZE_CV
    MIN_ALLOWED_SIZE
    HAS_BASE_ACCURACY
    EXPECTING_ENDPOINT_RE_SITES
    REJECTING_JUNCTION_RE_SITES
    // RE site matching
    ENZYME_NAME
    BLUNT_RE_TABLE
    OVERHANG5_RE_TABLE
// fillEnvVar(\our $SITE_CHROM_DATA_FILE,      'SITE_CHROM_DATA_FILE');     # in order of usage: first access the chrom's data
// fillEnvVar(\our $CLOSEST_SITE_LOOKUP_WRK,   'CLOSEST_SITE_LOOKUP_WRK');  # then find the closest site on the chrom to query pos1
// fillEnvVar(\our $SITE_DATA_LOOKUP_WRK,      'SITE_DATA_LOOKUP_WRK');     # then acquire the position and matching haplotypes
    // tolerances and thresholds
    CLIP_TOLERANCE      // RE site matching
    ACCEPT_ENDPOINT_DISTANCE
    REJECT_JUNCTION_DISTANCE
    MIN_TRAVERSAL_DELTA // block numbering
    MIN_MAPQ            
    MAX_DIVERGENCE
    MIN_FLANK_LEN
    MIN_AVG_BASE_QUAL
    // chimeric follow-on and internal adapter parameters
    INSERTION_WINDOW_SIZE
    MIN_INSERTION_WINDOW_QUAL
    INSERTION_ADAPTER_SEQUENCE
    MIN_ADAPTER_LENGTH // only look for adapters in junction inserts in this size range
    MAX_ADAPTER_LENGTH
    MIN_ADAPTER_SCORE  // empirically determined SW score that signals presence of an adapter in a junction insertion
    // target regions
    TARGETS_BED
    REGION_PADDING
// # output files
// fillEnvVar(\our $SITE_SAM_PREFIX,           'SITE_SAM_PREFIX');
// fillEnvVar(\our $FILTERED_INSERT_SIZES_FILE,'FILTERED_INSERT_SIZES_FILE');
// fillEnvVar(\our $FILTERED_STEM_LENGTHS_FILE,'FILTERED_STEM_LENGTHS_FILE');
    // derived values
    IS_END_TO_END_PLATFORM
    IS_PAIRED_READS
    IS_ONT
    IS_SIZE_SELECTED
    MAX_ALLOWED_SIZE
    SIZE_PLOT_BIN_SIZE
// # output files
// fillEnvVar(\our $SITE_SAM_PREFIX,           'SITE_SAM_PREFIX');
// fillEnvVar(\our $FILTERED_INSERT_SIZES_FILE,'FILTERED_INSERT_SIZES_FILE');
// fillEnvVar(\our $FILTERED_STEM_LENGTHS_FILE,'FILTERED_STEM_LENGTHS_FILE');
    // counter keys
    N_ALNS
    N_EVENTS
    N_READS_OUT
    N_READS_SV
    N_JXNS
    N_BLOCKS
    N_BAD_TRAVERSAL

    // @nJxnsRejected

    // keyed counter keys
    N_BY_GENOME
    N_DISCARDED
    N_BY_READ_OUTCOME
    // indexed counter keys
    N_BY_STEM_LENGTH

    
    // read outcomes
    KEPT_SEQUENCE 
    NONCANONICAL_CHROM 
    FAILED_SITE_LOOKUP
    TELOMERIC_FRAGMENT 
    CLIP_TOO_LARGE 
    DISTANCE_TOO_LARGE
    UNTRIMMED_ONT_ADAPTER
    IS_OFF_TARGET 

);
// const ONT_ADAPTER_LEN5: i32 = 34; // 3 empirically determined median adapter trim lengths 
// const TRIM5: usize = 0; // tl tag indices for 5' and 3' adapter trims
// const TRIM3: usize = 1;
// const FORWARD: u8 = 0;
// const REVERSE: u8 = 1;
const TARGET_SCALAR: f64 = 10.0;
const AVG_BASE_QUAL_BIN_SIZE: usize = 5;
    // discard reasons
    // KEPT_SEQUENCE           => "valid on-target reads passed to fragment analysis",
    // NONCANONICAL_CHROM      => "reads had their 5' alignment on a non-canonical chromosome",
    // FAILED_SITE_LOOKUP      => "reads failed site lookup",
    // TELOMERIC_FRAGMENT      => "reads were telomeric fragments",
    // CLIP_TOO_LARGE          => "reads had a clip that was too large",
    // DISTANCE_TOO_LARGE      => "reads had an outer site distance that was too large",
    // UNTRIMMED_ONT_ADAPTER   => "ONT reads lacked a 5' adapter trim",
    // IS_OFF_TARGET           => "reads had 5' (ONT) or all (other platforms) off-target alignment(s)",

// read junction statuses
const HAS_PASSED_JXN: &str  = "at least one passed junction";
const ALL_FAILED_JXNS: &str = "all failed junctions";
const HAS_NO_JXNS: &str     = "no junctions";
// read length types
const READ_LEN_PROPER: &str       = "nonSV.actual";
const PROJ_LEN_PROPER: &str       = "nonSV.projected";
const READ_LEN_CHIMERIC: &str     = "SV.chimeric"; // cannot assess projected size of structural variant reads
const READ_LEN_NON_CHIMERIC: &str = "SV.passed";   // these include all SV reads, not just translocations

// main ONT trim function called by hf3_tools main()
pub fn stream() -> Result<(), Box<dyn Error>> {

    // get config from environment variables
    let mut cfg = Config::new();
    cfg.set_string_env(&[
        SEQUENCING_PLATFORM, READ_PAIR_TYPE, READ_LENGTH_TYPE, ENZYME_NAME, 
        BLUNT_RE_TABLE, OVERHANG5_RE_TABLE, INSERTION_ADAPTER_SEQUENCE, TARGETS_BED]);
    cfg.set_usize_env(&[GENOME_SIZE, PLATFORM_MAX_INSERT_SIZE, MIN_SELECTED_SIZE, 
        MIN_ALLOWED_SIZE, CLIP_TOLERANCE, ACCEPT_ENDPOINT_DISTANCE, REJECT_JUNCTION_DISTANCE, 
        MIN_TRAVERSAL_DELTA, MIN_FLANK_LEN, INSERTION_WINDOW_SIZE, MIN_ADAPTER_LENGTH, 
        MAX_ADAPTER_LENGTH, MIN_ADAPTER_SCORE, REGION_PADDING]);
    cfg.set_f64_env(&[SELECTED_SIZE_CV, MAX_DIVERGENCE, MIN_AVG_BASE_QUAL, MIN_INSERTION_WINDOW_QUAL]);
    cfg.set_bool_env(&[IS_COMPOSITE_GENOME, IS_END_TO_END_READ, HAS_BASE_ACCURACY, 
        EXPECTING_ENDPOINT_RE_SITES, REJECTING_JUNCTION_RE_SITES]);
    cfg.set_u8_env(&[MIN_MAPQ]);

    // set derived config values
    cfg.set_bool( IS_END_TO_END_PLATFORM, cfg.get_bool(IS_END_TO_END_READ));
    cfg.set_bool( IS_PAIRED_READS,        cfg.equals_string(READ_PAIR_TYPE, "paired"));
    cfg.set_bool( IS_ONT,                 cfg.equals_string(SEQUENCING_PLATFORM, "ONT"));
    cfg.set_bool(IS_SIZE_SELECTED, cfg.get_usize(MIN_ALLOWED_SIZE) > 0 || 
                                              cfg.get_usize(MIN_SELECTED_SIZE) > 0);
    if cfg.get_usize(MIN_ALLOWED_SIZE) == 0 {
        cfg.set_usize(MIN_ALLOWED_SIZE, (*cfg.get_usize(MIN_SELECTED_SIZE) as f64 / 
                                                    (1.0 + cfg.get_f64(SELECTED_SIZE_CV))) as usize);
    }
    cfg.set_usize(MAX_ALLOWED_SIZE, cfg.get_usize(MIN_ALLOWED_SIZE) * 2);
    cfg.set_usize(SIZE_PLOT_BIN_SIZE, if cfg.equals_string(READ_LENGTH_TYPE, "short") { 10 } else { 250 });

    // initialize counters
    let mut ctrs = Counters::new(TOOL, vec![
        (COUNTER_SEPARATOR, "")
        (N_ALNS,            "input alignments"),
        (N_EVENTS,          "input events (single-end reads or read pairs)"),
        (N_READS_OUT,       "output reads (after splitting unmerged read pairs"),
        (COUNTER_SEPARATOR, "")

        (N_READS_SV,        "analyzed reads with >1 alignment"),
        (N_JXNS,            "junctions in analyzed SV reads)"),
        (N_BAD_TRAVERSAL,   "junctions failed traversal delta"), 
        (N_BLOCKS,          "output blocks"),
    ]);

    // initialize the tool
    let w = Worflow::new(TOOL, cfg, &mut ctrs);
    w.log.print("initializing");

    // build tool support resources
    let mut tool = Tool {
        chroms: Chroms::new(),
        // targets, load target regions, including target chroms from chroms, o/w nuclear chroms
    };

    // extract endpoints from each SAM record in a stream
    w.log.print("converting SAM to SITE_SAM with applied filters");
    let mut rs = RecordStreamer::new();
    rs
        .no_trim()
        .flexible()
        .group_by_in_place_serial(|alns: &mut Vec<SamRecord>| record_parser(
            alns, 
            &mut w,
            &mut tool,
        ), &["qname"]);

    // // report all unique observed positions with counts
    // log.print("printing endpoint tallies");
    // let mut sorted_keys: Vec<(usize, usize)> = endpoint_counter.keys().cloned().collect();
    // sorted_keys.sort_unstable();
    // for (chrom_index, site_pos1) in sorted_keys.iter() {
    //     println!(
    //         "{}\t{}\t{}",
    //         chroms.rev_index[&chrom_index],
    //         site_pos1,
    //         endpoint_counter[&(*chrom_index, *site_pos1)]
    //     );
    //     counters.increment(N_POS);
    // }

    // report counter values
    w.ctrs.print_all();
    // print reads by genome
    Ok(())
}

// # load dependencies
// map { require "$perlUtilDir/genome/$_.pl" } qw(targets);
// map { require "$perlUtilDir/sequence/$_.pl" } qw(smith_waterman);

// # constants
// use constant {
//     chrom_              => 0, # site index table columns
//     chromIndex_         => 1,
//     nSites_             => 2,
//     chromSize_          => 3,
//     closestSiteOffset_  => 4, # one lookup offset per chrom
//     siteDataOffset_     => 5,
//     #-------------
//     S_QNAME             => 0, # SITE_SAM fields
//     S_FLAG              => 1,
//     S_RNAME             => 2,
//     S_POS1              => 3,
//     S_MAPQ              => 4,
//     S_CIGAR             => 5,
//     SITE_INDEX1_1       => 6,
//     SITE_POS1_1         => 7,
//     SITE_DIST_1         => 8,
//     SITE_INDEX1_2       => 9,
//     SITE_POS1_2         => 10,
//     SITE_DIST_2         => 11,
//     SEQ_SITE_INDEX1_2   => 12,
//     SEQ_SITE_POS1_2     => 13,
//     IS_END_TO_END_READ  => 14,
//     IS_END_TO_END_INSERT=> 15,
//     NODE_5              => 16,
//     NODE_3              => 17,
//     CH_TAG              => 18,
//     TL_TAG              => 19,
//     INSERT_SIZE         => 20,
//     IS_ALLOWED_SIZE     => 21,
//     FM_TAG              => 22,
//     DE_TAG              => 23,
//     HV_TAG              => 24,
//     N_REF_BASES         => 25,
//     N_READ_BASES        => 26,
//     STEM5_LENGTH        => 27,
//     STEM3_LENGTH        => 28,
//     PASSED_STEM5        => 29,
//     PASSED_STEM3        => 30,
//     BLOCK_N             => 31,
//     ALN_FAILURE_FLAG    => 32,
//     JXN_FAILURE_FLAG    => 33,
//     TARGET_CLASS        => 34,
//     IS_ON_TARGET        => 35,
//     READ_HAS_JXN        => 36,
//     S_SEQ               => 37,
//     S_QUAL              => 38,
//     CS_TAG              => 39,
//     SAM_TAGS            => 40, # used and then discarded
//     # -------------
//     FALSE   => 0,
//     TRUE    => 1,
//     #-------------
//     TRIM5 => 0, 
//     TRIM3 => 1,
//     # -------------
//     EVENT   => 0,
//     READ1   => 1,
//     READ2   => 2,
//     #-------------
//     TOP_STRAND    => "", # signs for integer-encoded nodes
//     BOTTOM_STRAND => "-",
//     # -------------
//     ALN_FAIL_NONE            => 0,
//     ALN_FAIL_MAPQ            => 1,
//     ALN_FAIL_DIVERGENCE      => 2,
//     ALN_FAIL_FLANK_LEN       => 4,
//     ALN_FAIL_AVG_BASE_QUAL   => 8,
//     # -------------
//     JXN_FAIL_NONE            => 0,
//     JXN_FAIL_TRAVERSAL_DELTA => 1,
//     JXN_FAIL_NONCANONICAL    => 2,
//     JXN_FAIL_SITE_MATCH      => 4,
//     JXN_FAIL_FOLDBACK_INV    => 8,
//     JXN_FAIL_ONT_FOLLOW_ON   => 16, 
//     JXN_FAIL_HAS_ADAPTER     => 32,
// };
// my $READ_LEN_PROPER = READ_LEN_PROPER;
// my $PROJ_LEN_PROPER = PROJ_LEN_PROPER;
// my @nullSites = (0, 0, 0, 0, 0, 0);

// # open chrom-level output file handles
// my %chromHs;
// foreach my $chrom(@targetChroms){
//     my $chromFile = "$SITE_SAM_PREFIX.$chrom.site_sam.gz";
//     open my $chromH, "|-", "gzip -c > $chromFile" or die "could not open file: $chromFile: $!\n";
//     $chromHs{$chrom} = $chromH;
// }

// # print summary counts
// sub printSummaryCounts {
//     my $sep = "-------------\n";
//     print STDERR $sep;

//     # counts of all input reads and alignments
//     printCount(commify($nAlns),        'nAlns',        'input alignments');
//     printCount(commify($nInputEvents), 'nInputEvents', 'input events (single-end reads or read pairs)');
//     printCount(commify($nOutputReads), 'nOutputReads', 'output reads (after splitting unmerged read pairs)');
//     print STDERR $sep;

//     # report counts by genome when applicable
//     if($IS_COMPOSITE_GENOME){
//         foreach my $genome(sort keys %genomeCounts){
//             printCount(commify($genomeCounts{$genome} || 0), "5' read alignments mapped to genome $genome", '');
//         }
//         print STDERR $sep;
//     }

//     # counts of discarded reads by reason
//     foreach my $reason(
//         KEPT_SEQUENCE, 
//         NONCANONICAL_CHROM, 
//         FAILED_SITE_LOOKUP, TELOMERIC_FRAGMENT, CLIP_TOO_LARGE, DISTANCE_TOO_LARGE, # UNTRIMMED_ONT_ADAPTER
//         IS_OFF_TARGET
//     ){
//         printCount(commify($discardCounts{$reason} || 0), $reason, '');
//     }
//     print STDERR $sep;

//     # counts of alignment-level filter rejections
//     printCount(commify($nAlnsRejected[ALN_FAIL_NONE]          || 0), "alns passed all alignment-level filters", '');
//     printCount(commify($nAlnsRejected[ALN_FAIL_DIVERGENCE]    || 0), "alns were rejected with gap-corrected divergence > $MAX_DIVERGENCE", '');
//     printCount(commify($nAlnsRejected[ALN_FAIL_FLANK_LEN]     || 0), "alns were rejected with alignment length < $MIN_FLANK_LEN", '');
//     printCount(commify($nAlnsRejected[ALN_FAIL_AVG_BASE_QUAL] || 0), "alns were rejected with alignment avg. base QUAL < $MIN_AVG_BASE_QUAL", '');
//     # if(!$HAS_BASE_ACCURACY){
//     #     print STDERR "SV alignment avgBaseQuals\n";
//     #     for (my $avgBaseQual = 0; $avgBaseQual <= 50; $avgBaseQual += AVG_BASE_QUAL_BIN_SIZE){
//     #         my $bin = $avgBaseQual / AVG_BASE_QUAL_BIN_SIZE;
//     #         print STDERR join("\t", $avgBaseQual, $avgBaseQual[$bin] || 0), "\n";
//     #     }
//     # }
//     print STDERR $sep;

//     # counts of the structures of kept reads
//     printCount(commify($nSvReads),  'nSvReads',  'analyzed reads with >1 alignment');
//     printCount(commify($nJunctions),'nJunctions','junctions in analyzed SV reads');
//     printCount(commify($nFailedTraversal), 'nFailedTraversal', 'junctions failed traversal delta');
//     printCount(commify($nBlocks),          'nBlocks',          'output blocks');
//     print STDERR $sep;

//     # counts of junction-level filter rejections
//     printCount(commify($nJxnsRejected[JXN_FAIL_NONE]            || 0), "junctions passed all junction-level filters", '');
//     printCount(commify($nJxnsRejected[JXN_FAIL_TRAVERSAL_DELTA] || 0), "junctions were rejected with traversal delta < $MIN_TRAVERSAL_DELTA", '');
//     printCount(commify($nJxnsRejected[JXN_FAIL_NONCANONICAL]    || 0), "junctions were rejected with alignment to a non-canonical chromosome", '');
//     printCount(commify($nJxnsRejected[JXN_FAIL_SITE_MATCH]      || 0), "junctions were rejected due to junction RE site match within $REJECT_JUNCTION_DISTANCE bp", '');
//     printCount(commify($nJxnsRejected[JXN_FAIL_FOLDBACK_INV]    || 0), "junctions were rejected as foldback inversions", '');
//     printCount(commify($nJxnsRejected[JXN_FAIL_ONT_FOLLOW_ON]   || 0), "junctions were rejected as ONT follow-on artifacts", '');
//     printCount(commify($nJxnsRejected[JXN_FAIL_HAS_ADAPTER]     || 0), "junctions were rejected with detected adapter sequence", '');
//     print STDERR $sep;

//     # counts of read junction outcomes
//     foreach my $outcome($hasNoJxns, $hasPassedJxn, $allFailedJxns){
//         printCount(commify($readOutcomes{$outcome} || 0), "reads had $outcome", '');
//     }
//     print STDERR $sep;

//     # target counts
//     $nRegions and printTargetCounts($GENOME_SIZE);
//     print STDERR $sep;

//     # insert size counts and related distributions
//     printChimeraSummary();
// }
// printSummaryCounts();

// # process QNAME alignment groups, return read rejection reason for counting
// sub processOutputRead {

//     # check the ends of all alignments for RE site matches
//     # discard sequences if outer ends do not match within tolerance
//     # adjust outer site positions for clips
//     # reject sequences if, for a required outer endpoint:
//     #   outer clip is more than CLIP_TOLERANCE bp in length
//     #   clip-adjusted endpoint position is more than ACCEPT_ENDPOINT_DISTANCE bp away from closest RE site
//     #        *       *       *     proper sitePos1 values
//     #   ----|5-----3/5-----3|----  as nodes are numbered for alignments
//     #   ----|3-----5/3-----5|----
//     my ($isEndToEndRead, @trims);
//     my $tl = $alns[0][SAM_TAGS] =~ m/\ttl:Z:(\S+)/ ? $1 : "0,0";
//     foreach my $i(0..$#alns){
//         if($alns[$i][S_FLAG] & _REVERSE){ # outer endpoints are site matched even when EXPECTING_ENDPOINT_RE_SITES is FALSE if REJECTING_JUNCTION_RE_SITES is TRUE
//             @{$alns[$i]}[SITE_INDEX1_1..SITE_DIST_2] = $REJECTING_JUNCTION_RE_SITES ? (
//                 findClosestSite($alns[$i][S_RNAME], getEnd($alns[$i][S_POS1], $alns[$i][S_CIGAR]) + 1 - $correction5),
//                 findClosestSite($alns[$i][S_RNAME], $alns[$i][S_POS1] - $correction5)
//             ) : @nullSites;
//         } else {
//             @{$alns[$i]}[SITE_INDEX1_1..SITE_DIST_2] = $REJECTING_JUNCTION_RE_SITES ? ( 
//                 findClosestSite($alns[$i][S_RNAME], $alns[$i][S_POS1]),
//                 findClosestSite($alns[$i][S_RNAME], getEnd($alns[$i][S_POS1], $alns[$i][S_CIGAR]) + 1)
//             ) : @nullSites;
//         }
//         if($i == 0){ # read 5' end
//             if($REJECTING_JUNCTION_RE_SITES){
//                 $alns[$i][SITE_INDEX1_1] or return FAILED_SITE_LOOKUP;

//                 # reject telomeric fragments, i.e., that would cross past the first or last RE site on chrom
//                 if($alns[$i][S_FLAG] & _REVERSE){
//                     abs($alns[$i][SITE_INDEX1_1]) >  1 or return TELOMERIC_FRAGMENT;
//                 } else {
//                     abs($alns[$i][SITE_INDEX1_1]) <  ${$chromData{$alns[$i][S_RNAME]}}[nSites_] or return TELOMERIC_FRAGMENT;
//                 }
//             }

//             # get ONT adapter trims once per read
//             @trims = split(",", $tl);

//             # perform initial end-to-end status determination
//             $isEndToEndRead = (
//                 $isEndToEndPlatform or 
//                 ($isONT and $trims[TRIM3]) or # TODO: also check from 3' adapter trim on Aviti_1x300 and Ultima, i.e., add tl tag to those platforms
//                 ($isPairedReadPlatform and !$isUnmergedPair)
//             ) ? TRUE : FALSE;
//             # check 5' query end, always required to match a RE site
//             my $clip5 = 
//                 ($isONT and !$trims[TRIM5]) ?
//                 0 : # when ONT untrimmed, clip would include the adapter...
//                 (($alns[$i][S_FLAG] & _REVERSE) ? getRightClip($alns[$i][S_CIGAR]) : getLeftClip($alns[$i][S_CIGAR]));
//             $clip5 > $CLIP_TOLERANCE and return CLIP_TOO_LARGE;
//             if($EXPECTING_ENDPOINT_RE_SITES){
//                 my $dist5 = abs( ($alns[$i][S_FLAG] & _REVERSE) ? $alns[$i][SITE_DIST_1] + $clip5 : $alns[$i][SITE_DIST_1] - $clip5 );
//                 $dist5 > $ACCEPT_ENDPOINT_DISTANCE and return DISTANCE_TOO_LARGE;
//             }
//         }
//         if($i == $#alns){ # read 3' end
//             !$REJECTING_JUNCTION_RE_SITES or $alns[$i][SITE_INDEX1_2] or return FAILED_SITE_LOOKUP;

//             # aln3 is guaranteed by 'locate' to be between 1 and nSitesChrom

//             # 3' query end if an end-to-end sequence
//             # 3' ends on incomplete platforms/sequences are not _required_ to match an RE, but they may be found to do so below
//             my $clip3 = 
//                 ($isONT and !$trims[TRIM3]) ?
//                 0 :
//                 (($alns[$i][S_FLAG] & _REVERSE) ? getLeftClip($alns[$i][S_CIGAR]) : getRightClip($alns[$i][S_CIGAR]));
//             my $dist3 = abs( ($alns[$i][S_FLAG] & _REVERSE) ? $alns[$i][SITE_DIST_2] - $clip3 : $alns[$i][SITE_DIST_2] + $clip3 );
//             if($isEndToEndRead){
//                 $clip3 > $CLIP_TOLERANCE and return CLIP_TOO_LARGE;
//                 $EXPECTING_ENDPOINT_RE_SITES and $dist3 > $ACCEPT_ENDPOINT_DISTANCE and return DISTANCE_TOO_LARGE;
//             }

//             # promote incomplete sequences to end-to-end status if they got to the fragment end
//             $EXPECTING_ENDPOINT_RE_SITES and $dist3 <= $ACCEPT_ENDPOINT_DISTANCE and !$isUnmergedPair and $isEndToEndRead = TRUE;
//         }
//     }
//     my $inEndToEndInsert = ($isEndToEndRead or $isPairedReadPlatform) ? TRUE : FALSE;

//     # collect initial 3' site projections of each alignment
//     my $readHasJxn = @alns > 1 ? TRUE : FALSE;
//     foreach my $aln(@alns){
//         @$aln[SEQ_SITE_INDEX1_2..SEQ_SITE_POS1_2] = ($isEndToEndRead and !$readHasJxn) ?
//             @{$alns[-1]}[SITE_INDEX1_2..SITE_POS1_2] :
//             (0,0);
//         $$aln[SEQ_SITE_INDEX1_2] = abs($$aln[SEQ_SITE_INDEX1_2]);
//     }

//     # determine if the 5'-most alignment still needs to be projected
//     my ($node5, $node3);
//     if($EXPECTING_ENDPOINT_RE_SITES){
//         $alns[ 0][SEQ_SITE_INDEX1_2] or @{$alns[ 0]}[SEQ_SITE_INDEX1_2..SEQ_SITE_POS1_2] = getProjection($alns[0]);

//         # determine if the 3'-most alignment still needs to be projected
//         # here projection is more limited and simply bumps to the next RE site on any haplotype
//         $alns[-1][SEQ_SITE_INDEX1_2] or @{$alns[-1]}[SEQ_SITE_INDEX1_2..SEQ_SITE_POS1_2] = getProjection($alns[-1]);

//         # get outer nodes based on RE site positions
//         my $pairedSitePos1;
//         if($pairedAln5){
//             $pairedSitePos1 = (findClosestSite( # may not have assigned site position to other read yet for first read of unmerged pair
//                 $$pairedAln5[S_RNAME], 
//                 ($$pairedAln5[S_FLAG] & _REVERSE) ? getEnd($$pairedAln5[S_POS1], $$pairedAln5[S_CIGAR]) : $$pairedAln5[S_POS1],
//             ))[1] or return FAILED_SITE_LOOKUP;
//         }
//         $node5 = parseSignedNode( # reads always define their own 5' outer node
//             $alns[0], 
//             $alns[0][SITE_POS1_1], # using site positions enables fuzzy endpoint matching when comparing reads
//             BOTTOM_STRAND, TOP_STRAND
//         );
//         $node3 = $pairedAln5 ? 
//             parseSignedNode(
//                 $pairedAln5, 
//                 $pairedSitePos1,
//                 TOP_STRAND, BOTTOM_STRAND # invert the strand orientation of paired 5' ends to match the behavior of single or merged reads
//             ) : 
//             parseSignedNode(
//                 $alns[-1], 
//                 $alns[-1][SEQ_SITE_POS1_2],  # using projected 3' ends allows best deduplication of partially sequenced RE fragments
//                 BOTTOM_STRAND, TOP_STRAND
//             );

//     # get outer nodes based on alignment positions
//     } else {
//         $node5 =  parseSignedNode(
//             $alns[0], 
//             ($alns[0][S_FLAG] & _REVERSE) ? getEnd($alns[0][S_POS1], $alns[0][S_CIGAR]) : $alns[0][S_POS1], 
//             BOTTOM_STRAND, TOP_STRAND
//         );
//         $node3 = $pairedAln5 ? 
//             parseSignedNode(
//                 $pairedAln5, 
//                 ($$pairedAln5[S_FLAG] & _REVERSE) ? getEnd($$pairedAln5[S_POS1], $$pairedAln5[S_CIGAR]) : $$pairedAln5[S_POS1],
//                 TOP_STRAND, BOTTOM_STRAND
//             ) : 
//             parseSignedNode( # this unprojectable non-RE node position may not be the end of the insert if a single read is not end-to-end
//                 $alns[-1], 
//                 ($alns[-1][S_FLAG] & _REVERSE) ? $alns[-1][S_POS1] : getEnd($alns[-1][S_POS1], $alns[-1][S_CIGAR]), 
//                 BOTTOM_STRAND, TOP_STRAND
//             )
//     }

//     # collect next chunk of read-level metadata for passing into each alignment
//     my $ch = $alns[0][SAM_TAGS] =~ m/\tch:i:(\d+)/ ? $1 : 0;
//     my $readLen = length($alns[0][S_SEQ]);
//     my $insertSize = $isUnmergedPair ? -$node3 - $node5 : $readLen;
//     $isUnmergedPair and (
//         $eventHasJxn or 
//         $insertSize < 0 or
//         $insertSize > $PLATFORM_MAX_INSERT_SIZE or 
//         $alns[0][S_RNAME] ne $$pairedAln5[S_RNAME]
//     ) and $insertSize = 0; # when read carries any type of SV, whether sequenced or not, we cannot infer the true insert size
//     my $readStart0 = getQueryStart0($alns[ 0][S_FLAG], $alns[ 0][S_CIGAR]);
//     my $readEnd1   = getQueryEnd1(  $alns[-1][S_FLAG], $alns[-1][S_CIGAR], $readLen); # may not be the end of the insert
//     my $isAllowedSize = (!$isSizeSelected or ($insertSize >= $minAllowedSize and $insertSize <= $maxAllowedSize)) ? TRUE : FALSE;
//     foreach my $aln(@alns){
//         @$aln[IS_END_TO_END_READ..IS_ALLOWED_SIZE] = (
//             $isEndToEndRead, 
//             $inEndToEndInsert,
//             $node5, # like other read and insert-level properties, these repeat the same on all alignments
//             $node3, 
//             $ch, 
//             $tl, 
//             $insertSize, 
//             $isAllowedSize
//         );
//     }

//     # stop processing off-target reads, we have all required counts and they won't be used for variant calling
//     my $isOnTarget = $nRegions ? setAlnTargetClasses(@alns) : TRUE;
//     my $chromH = $chromHs{$samAlns[0][RNAME]};
//     ($isOnTarget and $chromH) or return IS_OFF_TARGET;

//     # add alignment-level metadata
//     my $blockN = 1;
//     foreach my $aln(@alns){
//         my $stem5Len = getQueryEnd1($$aln[S_FLAG], $$aln[S_CIGAR], $readLen) - $readStart0;
//         my $stem3Len = $isEndToEndRead ? $readEnd1 - getQueryStart0($$aln[S_FLAG], $$aln[S_CIGAR]) : 0;
//         my $fm = $$aln[SAM_TAGS] =~ m/\tfm:Z:(\S+)/ ? $1 : "0:0:0";
//         my $de = $$aln[SAM_TAGS] =~ m/\tde:f:(\S+)/ ? $1 : 0; # do not move these below
//         my $hv = $$aln[SAM_TAGS] =~ m/\thv:i:(\d+)/ ? $1 : 0;
//         my $cs = $$aln[SAM_TAGS] =~ m/\tcs:Z:(\S+)/ ? $1 : "*";
//         @$aln[
//             FM_TAG..READ_HAS_JXN,
//             CS_TAG
//         ] = (
//             $fm,
//             $de,
//             $hv,
//             getRefSpan($$aln[S_CIGAR]),     # N_REF_BASES
//             getAlignedSize($$aln[S_CIGAR]), # N_READ_BASES
//             $stem5Len,
//             $stem3Len,
//             (!$isSizeSelected or  $stem5Len < $minAllowedSize)                    ? TRUE : FALSE,
//             (!$isSizeSelected or ($stem3Len < $minAllowedSize and $stem3Len > 0)) ? TRUE : FALSE,
//             $blockN,
//             getAlnFailureFlag($aln, $de, $readHasJxn),
//             0, # JXN_FAILURE_FLAG
//             $$aln[TARGET_CLASS] || 0,
//             $isOnTarget,
//             0, # READ_HAS_JXN, NOT the same as $readHasJxn = @alns > 1, this will require JXN_FAILURE_FLAG == 0
//             #--------------------
//             $cs
//         );
//     }

//     # check junction read traversal delta for SV reads
//     my $anyJxnPassed = FALSE;
//     if(@alns > 1){
//         $nSvReads++;
//         $nJunctions += @alns - 1;

//         # assess traversal delta for every pair of alignments flanking every possible read sub-path
//         # fail all junctions within a failed path
//         # once a junction fails, it stays failed even if it passes a different pair of alignments
//         my @failedTraversalDelta = (0) x @alns;
//         foreach my $aln2I(1..$#alns){
//             foreach my $aln1I(0..($aln2I - 1)){
//                 failedTraversalDelta($alns[$aln1I], $alns[$aln2I], $readLen) and
//                     @failedTraversalDelta[($aln1I + 1)..$aln2I] = (1) x ($aln2I - $aln1I);
//             }
//         }

//         # update BLOCK_N based on failedTraversalDelta
//         foreach my $aln2I(1..$#alns){
//             $nFailedTraversal += $failedTraversalDelta[$aln2I];
//             $failedTraversalDelta[$aln2I] or $blockN++; # thus, increment alignment blockN on every non-failed junction
//             $alns[$aln2I][BLOCK_N] = $blockN;

//             # apply chimeric junction filters
//             $alns[$aln2I - 1][JXN_FAILURE_FLAG] = $failedTraversalDelta[$aln2I] ? 
//                 JXN_FAIL_TRAVERSAL_DELTA : 
//                 getJxnFailureFlag($alns[$aln2I - 1], $alns[$aln2I], $readLen);
//             $nJxnsRejected[$alns[$aln2I - 1][JXN_FAILURE_FLAG]]++;
//             $alns[$aln2I - 1][JXN_FAILURE_FLAG] or $anyJxnPassed = TRUE;
//         }
//     }
//     $nBlocks += $blockN;

//     # collect the distributions of insert sizes of on-target reads
//     my $sizeBin = int($insertSize / $sizePlotBinSize) * $sizePlotBinSize;
//     if($readHasJxn){ # disregard multi-junction reads when assessing insert sizes
//         @alns == 2 and $sizeBin and recordVariantSizes($sizeBin, @alns); 
//         $readOutcomes{$anyJxnPassed ? $hasPassedJxn : $allFailedJxns}++;
//     } else {
//         $sizeBin and $insertSizeCounts{$READ_LEN_PROPER}{$sizeBin}++;
//         my $projLen = $EXPECTING_ENDPOINT_RE_SITES ? 
//             abs($alns[0][SEQ_SITE_POS1_2] - $alns[0][SITE_POS1_1]) + 1 :
//             $insertSize;
//         $projLen and $insertSizeCounts{$PROJ_LEN_PROPER}{int($projLen / $sizePlotBinSize) * $sizePlotBinSize}++;
//         $readOutcomes{$hasNoJxns}++;
//     }

//     # print all alignment and return success
//     foreach my $aln(@alns){
//         $$aln[READ_HAS_JXN] = $anyJxnPassed;
//         print $chromH join("\t", @$aln[S_QNAME..CS_TAG]), "\n";
//     }

//     return KEPT_SEQUENCE;
// }

// # parse signed node representation for a read outer end
// sub parseSignedNode {
//     my ($aln, $pos1, $bottomStrand, $topStrand) = @_;
//     my $strandSign = ($$aln[S_FLAG] & _REVERSE) ? $bottomStrand : $topStrand;
//     $strandSign.$chromIndex{$$aln[S_RNAME]}.(sprintf "%09d", $pos1);
// }

1;
