---
pipeline:
    name: prepare
    description: "Perform one-time preparative actions on genomes prior to data analysis"
    version: v0.0.1
actions:
    _global:
        environment: hf3Main
        condaFamilies:
            - base
            - main
    genome:
        order: 1
        optionFamilies:
            - prepare-genome
            - digestion
        resources:
            required:
                total-ram: 8G
            recommended: 
                n-cpu: 1
                ram-per-cpu: 8G
        job-manager:
            recommended:
                time-limit: 4:00:00
        description: "download a reference genome and perform in silico digestion with blunt restriction enzymes"
package:
    genome: # the pipeline action after which a data package should assembled
        uploadType: hf3Digestion # a signal to the Stage 2 framework regarding the package contents
        files:
            summariesFile:
                type: rds
                file: $GENOME_PREFIX.RE_site_summaries.rds
            distributionsFile:
                type: rds
                file: $GENOME_PREFIX.RE_distributions.rds
# container:
#     supported: false    # set to true if you maintain a container registry for this pipeline [false]
#     registry:  ghcr.io  # domain name of your OCI-compatible, oras-accessible, container registry [ghcr.io]
#     owner:     wilsontelab # REQUIRED: the name of the owner, e.g., user or organization, at 'registry'
#     installer: apt-get  # the installer program used by the container OS, typically apt-get or yum [apt-get]
