---
pipeline:
    name: analyze
    description: "Align reads, match inserts to RE fragments, and find true mosaic variants"
    version: v0.0.1
actions:
    _global:
        environment: hf3Main
        condaFamilies:
            - base
            - main
        optionFamilies:
            - library-properties
            - genome
            - restriction-enzyme
    fragments:
        order: 1
        optionFamilies:
            - read-file
            - alignment
            - localization
            - targets
        resources:
            required:
                total-ram: 64G
            recommended: 
                n-cpu: 16
                ram-per-cpu: 6G
        job-manager:
            recommended:
                time-limit: 24:00:00
        description: "align reads to genome, match to RE sites, apply quality filters, scan for chimeras"
    SVs:
        order: 2
        optionFamilies:
            - targets
        #     - target-restriction
        resources:
            required:
                total-ram: 24G
            recommended: 
                n-cpu: 8 # fragment indexing, the slowest step, is parallelized by chromosome
                ram-per-cpu: 6G
        job-manager:
            recommended:
                time-limit: 12:00:00
        description: "parse prepared fragments to describe and count unique non-SV and SV paths"
    SNVs:
        order: 3
        optionFamilies:
            # - target-restriction
            - pileup
        resources:
            required:
                total-ram: 24G
            recommended: 
                n-cpu: 12
                ram-per-cpu: 8G
        job-manager:
            recommended:
                time-limit: 12:00:00
        description: "parse prepared fragments to describe and count unique SNV combinations"
package:
    SVs: # the pipeline action after which a data package should assembled
        uploadType: hf3AnalyzeSVs # a signal to the Stage 2 framework regarding the package contents
        files:
            chromsFile:
                type: txt
                file: $ANALYSIS_CHROMS_FILE
            filteringSitesBgz:
                type: txt.bgz
                file: $SITE_COLLECTION_BGZ
            filteringSitesTbi:
                type: txt.bgz.tbi
                file: $SITE_COLLECTION_BGZ.tbi
            genesBed:
                type: bed
                file: $GENES_BED
            targetsBed:
                type: bed
                file: $TARGETS_BED
            exclusionsBed:
                type: bed
                file: $GENOME_EXCLUSIONS_BED
            svJunctions1Bgz:
                type: txt.bgz
                file: $SV_MASKED_JUNCTIONS_FILE_1
            svJunctions1Tbi:
                type: txt.bgz.tbi
                file: $SV_MASKED_JUNCTIONS_FILE_1.tbi
            svJunctions2Bgz:
                type: txt.bgz
                file: $SV_MASKED_JUNCTIONS_FILE_2
            svJunctions2Tbi:
                type: txt.bgz.tbi
                file: $SV_MASKED_JUNCTIONS_FILE_2.tbi
            genomeTally:
                type: txt
                file: $GENOME_TALLY_FILE
            junctionTally:
                type: txt
                file: $JUNCTION_TALLY_FILE
            svAlignmentsBgz:
                type: txt.bgz
                file: $SV_ALIGNMENTS_FILE
                maxSize: 500M
            svAlignmentsTbi:
                type: txt.bgz.tbi
                file: $SV_ALIGNMENTS_FILE.tbi
                maxSize: 500M
            # svReadPaths:
            #     type: txt.gz
            #     file: $SV_READ_PATHS_FILE
    SNVs:
        uploadType: hf3AnalyzeSNVs
        files:
            snvSummaryBgz:
                type: txt.bgz
                file: $SNV_SUMMARY_TABLE
            snvSummaryTbi:
                type: txt.bgz.tbi
                file: $SNV_SUMMARY_TABLE.tbi
            readPileupGz:
                type: txt.gz
                file: $SNV_READ_PILEUP
# container:
#     supported: false    # set to true if you maintain a container registry for this pipeline [false]
#     registry:  ghcr.io  # domain name of your OCI-compatible, oras-accessible, container registry [ghcr.io]
#     owner:     wilsontelab # REQUIRED: the name of the owner, e.g., user or organization, at 'registry'
#     installer: apt-get  # the installer program used by the container OS, typically apt-get or yum [apt-get]
