# actions:
#   prepare aligned fragments for downstream variant analysis
#     purge unmapped reads
#     order alignments across each read from 5' to 3'
#     repack SAM to SITE_SAM for streamlined parsing
#     calculate the traversal delta over all sets of read alignments (across all sets of junctions) to set blockN
#         used to suppress spurious junctions arising in low quality regions with ~equal inserted and deleted bases
#     enforce alignment-level quality filtering with read truncation/cutting in 5' to 3' order
#         suppresses untrusted junctions arising from aligner issues
#     match alignment nodes to RE filtering sites
#     discard sequences where one or both complete outer nodes fail to match an RE filtering site
#     split chimeras at SV breakpoint nodes that match (discard distal/3' portion):
#         - RE sites (due to intermolecular ligation)
#         - foldback inversions (due to ONT duplex reads or inversion synthesis)
#         - low quality insertions (ONT only, to suppress follow-on chimeras)
#         - adapter insertions (due to any process that conjoins reads across an adapter)
#     project the 3' end of required alignments to the next RE site
# input:
#   NAME_BAM_FILE, as generated by `align` step 
#   CLOSEST_SITE_BINARY_FILE and others created by 'locate' step
#   config parameters:
#       ACCEPT_ENDPOINT_DISTANCE, stricter, for RE outer endpoints
#       REJECT_JUNCTION_DISTANCE, more permissive, thus rejects junction chimera more easily
# output:
#   SITE_SAM written to chromosome-level files in SITE_SAM_DIR

# variables
MATCH_DIR=${ACTION_DIR}/match_sites
UNMAPPED=4

# load the site lookup binaries into /dev/shm for fastest scanning
# production
echo "copying $ENZYME_NAME site lookup files to ram disk"
cp $CLOSEST_SITE_LOOKUP $TMP_DIR_WRK_SHM
cp $SITE_DATA_LOOKUP    $TMP_DIR_WRK_SHM
export CLOSEST_SITE_LOOKUP_WRK=$TMP_DIR_WRK_SHM/`basename $CLOSEST_SITE_LOOKUP`
export SITE_DATA_LOOKUP_WRK=$TMP_DIR_WRK_SHM/`basename $SITE_DATA_LOOKUP`
# debugging
# export CLOSEST_SITE_LOOKUP_WRK=$CLOSEST_SITE_LOOKUP
# export SITE_DATA_LOOKUP_WRK=$SITE_DATA_LOOKUP
echo "parsing alignments to quality-filtered, RE-matched, error-corrected fragments and reads"

# working per alignment:
#   purge unmapped reads/empty alignments and convert to SAM
samtools view --threads $SAMTOOLS_CPU --exclude-flags $UNMAPPED $NAME_BAM_FILE | 

# working per event:
#   PENDING: enforce zoo rejection
#   order alignments across each read from 5' to 3'
#   repack SAM to SITE_SAM for streamlined parsing
#   record number of aligned read bases and associated ref span
perl ${MATCH_DIR}/order_alignments.pl |

# working per read:
#   calculate the reference vs. read traversal delta between all sets of alignments (across all sets of junctions)
#   use calculated deltas and MIN_TRAVERSAL_DELTA to set BLOCK_N of all alignments
#   junctions between alignments with the same BLOCK_N may be considered artifactual during SV analysis
#   block numbering is done before alignment quality truncation when all read alignments are still present
#   SVs that fail block traversal checks may or may not be split by downstream quality filters
perl ${MATCH_DIR}/check_traversal_delta.pl | 

# working per sequence:
#   check whether alignments pass alignment-level quality filters
#   when an alignment fails, remove it and all alignments further 3' on the read
#   must come after order_alignments as quality filtering is executed from 5' to 3' on read
perl ${MATCH_DIR}/enforce_quality_filters.pl |

# working per alignment:
#   find the nearest filtering RE site to each alignment node and the direction to it
perl ${MATCH_DIR}/match_nodes_to_sites.pl |

# working per sequence:
#   reject and discard sequences that don't match RE sites at complete outermost endpoints
#       disregard incomplete 3' ends when applying this filter
#   fill the sequence 3' site fields end when already known for end-to-end/complete sequences with no SV
perl ${MATCH_DIR}/discard_unmatched_sequences.pl | 

# working per read:
#   split SV junctions that match RE sites or are otherwise identified as chimeras
#   in particular, reads are also processed for adapter presence, ONT follow-ons, and foldback inversion chimeras
#   discard the distal/3' portion of split chimeric reads as unusable, retaining the 5' end
perl ${MATCH_DIR}/split_chimeric_reads.pl | 

# working per read:
#   when not set above, project the 3' end of required alignments to the next RE site
#   assess the proper fragment insert size distribution
#   assess whether alignment/read ends matched a target region, if TARGETS_BED provided
#   print SITE_SAM to chromosome-level file in preparation for variant analysis
perl ${MATCH_DIR}/project_incomplete_reads.pl
