---
pipeline:
    name: compare
    description: "Compare variants called by the analyze pipeline across multiple related samples"
    version: v0.0.1
actions:
    _global:
        environment: hf3Main
        condaFamilies:
            - base
            - main
        optionFamilies:
            - genome
    SVs:
        order: 1
        optionFamilies:
            - compare
        resources:
            required:
                total-ram: 12G
            recommended: 
                n-cpu: 2 # fragment indexing, the slowest step, is parallelized by chromosome
                ram-per-cpu: 6G
        job-manager:
            recommended:
                time-limit: 2:00:00
        description: "compare structural variant junctions between multiple related samples"
    # SNVs:
    #     order: 2
    #     optionFamilies:
    #         - compare
    #         # - target-restriction
    #         - pileup
    #     resources:
    #         required:
    #             total-ram: 24G
    #         recommended: 
    #             n-cpu: 12
    #             ram-per-cpu: 8G
    #     job-manager:
    #         recommended:
    #             time-limit: 12:00:00
    #     description: "parse prepared fragments to describe and count unique SNV combinations"
package:
    SVs: # the pipeline action after which a data package should assembled
        uploadType: hf3CompareSVs # a signal to the Stage 2 framework regarding the package contents
        files:
            chromsFile:
                type: txt
                file: $ANALYSIS_CHROMS_FILE
            genesBed:
                type: bed
                file: $GENES_BED
            exclusionsBed:
                type: bed
                file: $GENOME_EXCLUSIONS_BED
            svJunctions1Bgz:
                type: txt.bgz
                file: $SV_MASKED_JUNCTIONS_FILE_1
            svJunctions1Tbi:
                type: txt.bgz.tbi
                file: $SV_MASKED_JUNCTIONS_FILE_1.tbi
            svJunctions2Bgz:
                type: txt.bgz
                file: $SV_MASKED_JUNCTIONS_FILE_2
            svJunctions2Tbi:
                type: txt.bgz.tbi
                file: $SV_MASKED_JUNCTIONS_FILE_2.tbi
#     SNVs:
#         uploadType: hf3AnalyzeSNVs
#         files:
#             snvSummaryBgz:
#                 type: txt.bgz
#                 file: $SNV_SUMMARY_TABLE
#             snvSummaryTbi:
#                 type: txt.bgz.tbi
#                 file: $SNV_SUMMARY_TABLE.tbi
#             readPileupGz:
#                 type: txt.gz
#                 file: $SNV_READ_PILEUP
# container:
#     supported: false    # set to true if you maintain a container registry for this pipeline [false]
#     registry:  ghcr.io  # domain name of your OCI-compatible, oras-accessible, container registry [ghcr.io]
#     owner:     wilsontelab # REQUIRED: the name of the owner, e.g., user or organization, at 'registry'
#     installer: apt-get  # the installer program used by the container OS, typically apt-get or yum [apt-get]
