use strict;
use warnings;

# action:
#   describe the SV paths of all reads
#       for now, even those out of allowable size range
#   use a streamlined, reduced-representation fragment index to count unique paths
#   work is parallelized by chromosome for speed gains and sorting efficiency
#   this script is applicable to all sequencing platforms
#   SV paths are described by:
#       site5 = the 5'-most matching fragment RE site (previously required to match a RE site)
#       isEndToEnd = 0|1 indicating whether site3 is actual or projected, if 1/TRUE, site3 is actual
#           when isEndToEnd == 1, the last distalNode is redundant with site3
#       distalNodes = a colon-delimited list of more distal/3' nodes (just the 3'-most node if no SV in read)
#       junctions = a colon-delimited list of SV junctions between the nodes ("*" if no SV in read)
#       site3 = the 3'-most matching fragment RE site (either actual or projected)
#       readHasSv = 0|1 indicating whether this read has a SV
#   where a matching fragment RE site is described as:
#       chromIndex1,siteIndex1,strandIndex0 (thus, a reduced number of possibilities), where
#           chromIndex1  = 1-based index of ordered chromosomes
#           siteIndex1   = 1-based index of RE site along a chromosome
#           strandIndex0 = 0 for top strand, 1 for bottom strand sequence
#   a distal/3' junction node is described as:
#       chromIndex1,refPos1,strandIndex0 (previously required to NOT match an RE site at junctions), where
#           refPos1 = 1-based coordinate of the last aligned base in the chromosome
#   and an SV junction is described by read-dependent properties that can't be derived from nodes:
#       alignmentOffset,jxnBases, where
#           alignmentOffset = number of non-reference bases found at junction (negative if microhomology)
#           jxnBases = the inserted or microhomologous bases (omitted for long ONT sequences)
#   junctions were already split upstream at low quality alignments and chimeras
#   junctions and associated distal nodes are omitted here, as if they didn't exist,
#       when blockN of the two flanking alignments is the same, i.e., the junction failed traversalDelta checks
#       since the most likely true path was contiguous across that (portion of the) read
#   the indexing strategy exploits numeric indices to sort by:
#       site5[chromIndex1][siteIndex1][strandIndex0]
#       i.e., such that the read 5' end defines the parent location of an SV path
#   a hash is used to track the unique paths encountered for each unique 5' end as:
#       isEndToEnd::distalNodes::junctions::site3::readHasSv
#   indexing occurs with respect to read strand, so reads are NOT aggregated by strand
#       i.e., a variant sequenced in two strand orientations will be found on at least two indexed lines
#   multiple independent indexed lines may exist for a clonal variant if sequencing errors give distinct hash keys
#   indexing is an aggregating action, so read/event identifiers are lost in the index
#   to allow indexed SV paths to be correlated back to source reads, especially for ONT duplex purging
#       a list is saved of all pre-aggregation SV paths with their associated QNAME and ONT channel
#       as with the index, different paths in the list may be non-identical but with the same SV due to sequencing errors
# input:
#   SITE_SAM files generated by `analyze fragments`, one file per chromosome
#   FILTERING_SITES_FILE, i.e. the set of RE filtering sites identified by `locate`
# output:
#   alignment-level files, with event counts, used for generating fragment maps:
#       FIRST_ALIGNMENTS    = the single alignment at the 5' end of a read
#                               implicitly sorted by site5 sitePos1 as a result of indexing
#       DISTAL_ALIGNMENTS   = the alignment(s) after SV junction(s) in the read
#                               sorted by coordinate after downstream aggregation to genome-level files
#                               last distal alignment carries information on the distance from site3 sitePos1 to refPos1_2
#           all alignment files carry information on three nodes (even if empty==0)
#               refPos1_5 = the 5'-most base in the alignment (node1)
#               refPos1_2 = the 3'-most base in the alignment (node2)
#               refPos1_3 = the 3'-most base in the RE fragment (0 if not known, not applicable, not projected)
#           alignment nodes are in 5' to 3' order on the read, i.e., refPos1_5 is > refPos1_2 when strandIndex0 == 1
#   junction-level files, used for establishing SV uniqueness and zygosity:
#       JUNCTION_SOURCES    = one line per pre-aggregation junction with source QNAME and ONT channel
#       UNIQUE_JUNCTIONS    = one line per post-aggregation junction with event counts
#           junction nodes are sorted such that:
#               SVs encountered on different strands have the same node1 and node2 order
#               column strandIndex0 indicates the source strand/orientation, i.e., is true==1 when flipped relative to the read
#           junction nodes are not yet aggregated for fuzzy-logic proximity matching or ONT duplex purging
#   note that :
#       most alignments are in FIRST_ALIGNMENTS
#       DISTAL_ALIGNMENTS all come from SV molecules
#   all output files are, at least initially, one file per _indexing_ chromosome
#       only entries in FIRST_ALIGNMENTS are guaranteed to reside on the indexing chromosome
#       all other files are aggregated into coordinate-sorted genome-level files in the next action step

# initialize reporting
our $script = "index_fragments";
our $error  = "$script error";

# load dependencies
my $perlUtilDir = "$ENV{MODULES_DIR}/utilities/perl";
map { require "$perlUtilDir/$_.pl" } qw(workflow numeric);
map { require "$perlUtilDir/genome/$_.pl" } qw(chroms targets);
map { require "$perlUtilDir/sequence/$_.pl" } qw(general faidx);
resetCountFile();

# environment variables
# genome
fillEnvVar(\my $GENOME_FASTA_SHM,        'GENOME_FASTA_SHM');
# platform and library properties
fillEnvVar(\my $SEQUENCING_PLATFORM,     'SEQUENCING_PLATFORM');
# RE site matching
fillEnvVar(\my $FILTERING_SITES_FILE,    'FILTERING_SITES_FILE');
# tolerances and thresholds
fillEnvVar(\my $MAX_JXN_BASES,           'MAX_JXN_BASES');
# target regions
fillEnvVar(\our $TARGETS_BED,            'TARGETS_BED');
fillEnvVar(\our $REGION_PADDING,         'REGION_PADDING');
# input files
fillEnvVar(\my $SITE_SAM_PREFIX,         'SITE_SAM_PREFIX');
# output files
fillEnvVar(\my $SAMPLE_PATHS_PREFIX_WRK, 'SAMPLE_PATHS_PREFIX_WRK');
fillEnvVar(\my $N_CPU,                   'N_CPU');

# set derived variables
my $isONT = ($SEQUENCING_PLATFORM eq "ONT");
my $isTargeted = ($TARGETS_BED and $TARGETS_BED ne "null" and $TARGETS_BED ne "NA");
our $TARGET_SCALAR = 10;

# constants
use constant {
    S_QNAME             => 0, # SITE_SAM fields
    S_FLAG              => 1,
    S_RNAME             => 2,
    S_POS1              => 3,
    S_MAPQ              => 4,
    S_CIGAR             => 5,
    SITE_INDEX1_1       => 6,
    SITE_POS1_1         => 7,
    SITE_DIST_1         => 8,
    SITE_INDEX1_2       => 9,
    SITE_POS1_2         => 10,
    SITE_DIST_2         => 11,
    SEQ_SITE_INDEX1_2   => 12,
    SEQ_SITE_POS1_2     => 13,
    IS_END_TO_END       => 14,
    CH_TAG              => 15,
    TL_TAG              => 16,
    INSERT_SIZE         => 17,
    IS_ALLOWED_SIZE     => 18,
    DE_TAG              => 19,
    HV_TAG              => 20,
    N_REF_BASES         => 21,
    N_READ_BASES        => 22,
    STEM5_LENGTH        => 23,
    STEM3_LENGTH        => 24,
    PASSED_STEM5        => 25,
    PASSED_STEM3        => 26,
    BLOCK_N             => 27,
    ALN_FAILURE_FLAG    => 28,
    JXN_FAILURE_FLAG    => 29,
    TARGET_CLASS        => 30,
    END5_ON_TARGET      => 31,
    READ_HAS_JXN        => 32,
    S_SEQ               => 33,
    S_QUAL              => 34,
    CS_TAG              => 35,
    #-------------
    SPLIT_TO_S_QUAL     => 36,
    #-------------
    _IS_PAIRED      => 1,  # SAM FLAG bits
    _PROPER_PAIR    => 2,
    _UNMAPPED       => 4,
    _MATE_UNMAPPED  => 8,
    _REVERSE        => 16,
    _MATE_REVERSE   => 32,
    _FIRST_IN_PAIR  => 64,
    _SECOND_IN_PAIR => 128,
    _SECONDARY      => 256,
    _FAILED_QC      => 512,
    _DUPLICATE      => 1024,
    _SUPPLEMENTAL   => 2048,
    #-------------
    FALSE  => 0,
    TRUE   => 1,
    #-------------
    TOP_STRAND    => 0,
    BOTTOM_STRAND => 1,
    #-------------
    ALN_HAS_SNV         => 1, # variant flag bits
    READ_HAS_SNV        => 2,
    READ_HAS_SV         => 4,
    READ_HAS_VARIANT    => 8,
    #-------------
    NULL_ENTRY      => "*",
    NULL_JUNCTION   => "*,*",
    NULL_JXN_BASES  => "#", # the value used when junction bases were not processed, but alignment offset is present
    #-------------
    PATH_IS_END_TO_END    => 0,
    PATH_DISTAL_NODES     => 1,
    PATH_JUNCTIONS        => 2,
    PATH_SITE3            => 3,
    #-------------
    SITE3_CHROM_INDEX1  => 0,
    SITE3_SITE_INDEX1   => 1,
    SITE3_STRAND_INDEX0 => 2,
    #-------------
    NODE_CHROM_INDEX1   => 0,
    NODE_REF_POS1       => 1,
    NODE_STRAND_INDEX0  => 2,
    #-------------
    TYPE_PROPER         => 0, # junction/edge types
    TYPE_DELETION       => 1,
    TYPE_DUPLICATION    => 2,
    TYPE_INVERSION      => 3,
    TYPE_TRANSLOCATION  => 4,
    #-------------
    OJXN_CHROM_INDEX1_1     => 0,
    OJXN_REF_POS1_1         => 1,
    OJXN_STRAND_INDEX0_1    => 2,
    OJXN_CHROM_INDEX1_2     => 3,
    OJXN_REF_POS1_2         => 4,
    OJXN_STRAND_INDEX0_2    => 5,
    OJXN_JXN_TYPE           => 6,
    OJXN_ALN_OFFSET         => 7,
    OJXN_JXN_BASES          => 8,
    OJXN_ORIENTATION        => 9,
    #-------------
    ALN_TARGET_CLASS_BITS => 7, # bitmask to extract an alignment's own target class from TARGET_CLASS
    # "--" => 0, # the possible values of one alignment's target class, requires three bits to store
    # "TT" => 1,
    # "TA" => 2,
    # "T-" => 3,
    # "AA" => 4,
    # "A-" => 5
    #-------------
    NODE1 => 0,
    NODE2 => 1,
    #-------------
    JXN_ALN_OFFSET   => 0,
    JXN_JXN_BASES    => 1,
    JXN_JXN_TYPE     => 2, # added after indexing
};

# working variables
our (
    $chrom, $chromIndex1, $paddedChromIndex1, @sites,
    $prevRead, @alns, @index,
    $siteIndex1, $strandIndex0, $varKey, $faH
);

# initialize the target regions, if any
use vars qw($nRegions);
loadTargetRegions();

# initialize the genome
print STDERR "collecting chrom index\n";
use vars qw(%chromIndex);
setCanonicalChroms();
my @nuclearChroms = getNuclearChroms();
# my %nuclearChroms = map { $_ => 1 } @nuclearChroms;
our @targetChroms = $nRegions ? getTargetChroms() : @nuclearChroms;
loadFaidx($GENOME_FASTA_SHM);

# initialize the conversion from site indices to positions
# once the index is used, it is more informative to track site reference coordinates
print STDERR "loading site positions\n";
open my $sitesH, "-|", "zcat $FILTERING_SITES_FILE" or die "could not open sites file: $FILTERING_SITES_FILE: $!\n";
my $discardHeader = <$sitesH>;
my ($siteIndex1_, $prevChrom) = (0);
while (my $site = <$sitesH>){ # chrom   sitePos1   inSilico   nObserved
    my ($chrom, $sitePos1) = split("\t", $site);
    $prevChrom and $prevChrom ne $chrom and $siteIndex1_ = 0;
    $siteIndex1_++;
    $sites[$chromIndex{$chrom}][$siteIndex1_] = $sitePos1;
    $prevChrom = $chrom;
}
close $sitesH;

# parallelize by chromosome for speed
# user responsible for setting N_CPU to prevent memory overruns
print STDERR "indexing alignments by chromosome\n";
$| = 1;
launchChildThreads(\&processChroms);
use vars qw(@readH @writeH);
my $writeH = $writeH[1];
# foreach my $chrom("chr21", "chr22"){
# foreach my $chrom("chr1"){
foreach my $chrom(@targetChroms){
    my $chromIndex1 = $chromIndex{$chrom} or next;
    $writeH = $writeH[$chromIndex1 % $N_CPU + 1];
    print $writeH join("\t", $chrom, $chromIndex1), "\n";
}
finishChildThreads();

# parse input SAM
sub processChroms {
    my ($childN) = @_;
    my $readH = $readH[$childN];

    # open this thread's handle to genome FASTA for pseudo reference contig assembly
    open $faH, "<", $GENOME_FASTA_SHM or die "could not open $GENOME_FASTA_SHM: $!\n";

    # process data by chrom
    while(my $line = <$readH>){
        chomp $line;

        # open the chromosome-specific site_sam file created by `analyze fragments`
        ($chrom, $chromIndex1) = split("\t", $line);
        my $chromFile = "$SITE_SAM_PREFIX.$chrom.site_sam.gz";

        #############################
        # open my $chromH, "-|", "zcat $chromFile | head -n 1000000" or die "$error: could not open: $chromFile: $!\n";
        open my $chromH, "-|", "zcat $chromFile" or die "$error: could not open: $chromFile: $!\n";

        # open caller-specific, chromosome-level output file handles
        # do now in case caller wants to print during indexing
        # use zero-padded chrom indices to allow simple lexical sort of file names
        $paddedChromIndex1 = sprintf("%02d", $chromIndex1);
        openFileHandles();
        
        # index reads one at a time, counting unique encountered variant patterns per RE fragment
        # indexing action is defined by the calling script
        print STDERR "  $chrom\tassembling index\n";
        ($prevRead, @alns, @index) = ();
        while(my $aln = <$chromH>){
            chomp $aln;
            my @aln = split("\t", $aln, SPLIT_TO_S_QUAL);
            if($prevRead and $prevRead ne $aln[S_QNAME]){
                my $key = indexRead();
                $key and $index[ abs($alns[0][SITE_INDEX1_1]) ][ ($alns[0][S_FLAG] & _REVERSE) ? BOTTOM_STRAND : TOP_STRAND ]{ $key }++;
                @alns = (); # don't reset @index of course
            }
            push @alns, \@aln;
            $prevRead = $aln[S_QNAME];
        }
        if(@alns){ # catch for siteless chromosomes
            my $key = indexRead();
            $key and $index[ abs($alns[0][SITE_INDEX1_1]) ][ ($alns[0][S_FLAG] & _REVERSE) ? BOTTOM_STRAND : TOP_STRAND ]{ $key }++;
        }
        close $chromH;

        # unpack unique encountered variants
        # print to output formats as performed by the calling script
        print STDERR "  $chrom\tsorting and printing\n";
        my $i = 1;
        foreach $siteIndex1(1..$#index){
            $index[$siteIndex1] or next;
            foreach $strandIndex0(BOTTOM_STRAND, TOP_STRAND){
                my $vars = $index[$siteIndex1][$strandIndex0] or next;
                foreach $varKey(sort { $$vars{$b} <=> $$vars{$a} } keys %$vars){ # most frequent variant pattern sorts first
                    printIndexedVariant($i, $$vars{$varKey});
                    $i++;
                }
            }
        }
        closeFileHandles();
    }
    close $faH;
}

# open/close the required chromosome-level output files
our ($jxnSrcH, $uniqJxnH, $firstAlnH, $distalAlnH, $alnSizeH, $readPathH);
sub openFileHandles {
    open $jxnSrcH,    "|-", "gzip -c > $SAMPLE_PATHS_PREFIX_WRK.junction_sources.$paddedChromIndex1.txt.gz"  or die "could not open jxnSrcH: $!\n";
    open $uniqJxnH,   "|-", "gzip -c > $SAMPLE_PATHS_PREFIX_WRK.unique_junctions.$paddedChromIndex1.txt.gz"  or die "could not open uniqJxnH: $!\n";
    open $firstAlnH,  "|-", "gzip -c > $SAMPLE_PATHS_PREFIX_WRK.first_alignments.$paddedChromIndex1.txt.gz"  or die "could not open firstAlnH: $!\n";
    open $distalAlnH, "|-", "gzip -c > $SAMPLE_PATHS_PREFIX_WRK.distal_alignments.$paddedChromIndex1.txt.gz" or die "could not open distalAlnH: $!\n";
    open $alnSizeH,   "|-", "gzip -c > $SAMPLE_PATHS_PREFIX_WRK.alignment_sizes.$paddedChromIndex1.txt.gz"   or die "could not open alnSizeH: $!\n";
    open $readPathH,  "|-", "gzip -c > $SAMPLE_PATHS_PREFIX_WRK.read_paths.$paddedChromIndex1.txt.gz"        or die "could not open readPathH: $!\n";
}
sub closeFileHandles {
    close $jxnSrcH;
    close $uniqJxnH;
    close $firstAlnH;
    close $distalAlnH;
    close $alnSizeH;
    close $readPathH;
}

# create a hash key for a read and count it in the index
sub indexRead {

    # collect the unstranded outer endpoints for ONT duplex purging
    # including ONT channel allows duplicates sequenced in different channels to persist
    # NA for other platforms since RE-cleaved libraries expected to be PCR-free with no duplicates
    # using site indices instead of alignment positions yields fuzzy matching of outer endpoints
    my ($outerEndpoints, $isReordered) = $isONT ? 
        getOuterEndpoints_ONT(
            $chromIndex1,                        abs($alns[0][SITE_INDEX1_1]),
            $chromIndex{$alns[$#alns][S_RNAME]}, $alns[$#alns][SEQ_SITE_INDEX1_2],
            $alns[0][CH_TAG]
        ) : 
        getOuterEndpoints(
            $chromIndex1,
            $chromIndex{$alns[$#alns][S_RNAME]}
        );

    # print alignment sizes for library deduplication and summation downstream
    foreach my $alnI0(0..$#alns){
        print $alnSizeH join("\t", 
            $outerEndpoints, # chromIndex1_1,chromIndex1_2 OR chromIndex1_1,siteIndex1_1,chromIndex1_2,siteIndex1_2,channel
            # $end5OnTarget, # all indexed reads are now on-target for targeted libraries
            $isReordered ? ($#alns - $alnI0) : $alnI0, # (reordered) alnI0
            $alns[$alnI0][N_REF_BASES], 
            $alns[$alnI0][N_READ_BASES]
        ), "\n";
    }

    # assemble the parts of the SV path key
    my (@distalNodes, @junctions);
    if(@alns > 1){
        foreach my $i(1..$#alns){ # internal nodes and junctions
            unless($alns[$i - 1][BLOCK_N] == $alns[$i][BLOCK_N]){
                push @distalNodes, getNode2($alns[$i - 1]);
                push @distalNodes, getNode1($alns[$i]);
                push @junctions, getJunction($alns[$i - 1], $alns[$i]);
            }
        }
    }
    push @distalNodes, getNode2($alns[$#alns]);
    @junctions or @junctions = (NULL_ENTRY);

    # save junction sources with QNAME, ONT channel and other event metadata for ONT duplex purging and other needs
    unless($junctions[0] eq NULL_ENTRY){
        $outerEndpoints =~ s/\t/:/g;
        for(my $i = 0; $i < $#distalNodes; $i += 2){
            my $aln1I = $i / 2;
            my $seqI = $alns[$aln1I][S_SEQ] eq "*" ? $aln1I + 1 : $aln1I; # obsolete? SEQ and QUAL no longer masked on SV reads

            # replace commas in fields that must be concatenated downstream
            # this includes by bedtools groupby, which only offers comma delimiters
            # S_QNAME, CH_TAG, S_SEQ, S_CIGAR, S_MAPQ, and DE_TAG are comma-safe as is
            $alns[$seqI][S_QUAL] =~ s/,/+/g; # one value poorer quality than comma on the ASCII table

            print $jxnSrcH join("\t", # print SV_JUNCTION_SOURCES_FILE

                # these values describe the junction itself
                # chrom1,pos1,strand1,chrom2,pos2,strand2,jxnType,alnOffset,jxnBases,wasInverted
                orientJunction($distalNodes[$i], $distalNodes[$i + 1], $junctions[$i / 2]),

                # these values are the same for all read alignments (even those not flanking the junction)
                $alns[0][S_QNAME],
                $alns[0][CH_TAG],
                $alns[0][INSERT_SIZE],
                $alns[0][IS_ALLOWED_SIZE],
                $outerEndpoints, # ordered outer endpoints for duplicate purging
                # $end5OnTarget, # all indexed reads are now on-target for targeted libraries

                # these values aggregate the two flanking alignments to a single statistic
                min(    $alns[$aln1I][STEM5_LENGTH],     $alns[$aln1I + 1][IS_END_TO_END] ? $alns[$aln1I + 1][STEM3_LENGTH] : 1e9),
                max(    $alns[$aln1I][PASSED_STEM5],     $alns[$aln1I + 1][IS_END_TO_END] ? $alns[$aln1I + 1][PASSED_STEM3] : 0),
                min(    $alns[$aln1I][S_MAPQ],           $alns[$aln1I + 1][S_MAPQ]),
                max(    $alns[$aln1I][DE_TAG],           $alns[$aln1I + 1][DE_TAG]),
                min(abs($alns[$aln1I][SITE_DIST_2]), abs($alns[$aln1I + 1][SITE_DIST_1])), # unsigned shortest distance to a site
                max(    $alns[$aln1I][ALN_FAILURE_FLAG], $alns[$aln1I + 1][ALN_FAILURE_FLAG]),
                $alns[$aln1I][JXN_FAILURE_FLAG], # read might have one failed and one passed junction

                # these values are shared by the flanking alignments
                # we do not duplicate SEQ and QUAL as it is the same for the alignments
                # but recognize that SEQ and QUAL may be reverse complemented for aln2 relative to aln1,
                # where SEQ and QUAL are provided in aln1 orientation
                # importantly, unlike readPaths, SEQ and QUAL are reference, not read, oriented
                #    i.e. they always match the reference genome sequence and may be rc'ed relative to the read
                # need strandIndex0 and wasInverted to interpret SEQ and QUAL orientation
                $alns[$seqI][S_SEQ],
                $alns[$seqI][S_QUAL],

                # these values concatenate pairs of alignment-level properties of the two flanking alignments
                # use double-colon to separate instances (to retain potential for colon-delimited alignment tags in the future)
                join("::", $alns[$aln1I][S_CIGAR], $alns[$aln1I + 1][S_CIGAR])
            ), "\n";
        }

        # print the path of each read as a concatenated reference sequence across all read junctions
        # used for read-level visualization
        my $qLen = $alns[0][INSERT_SIZE];
        my $readSeq  = ($alns[0][S_FLAG] & _REVERSE) ?   getRc($alns[0][S_SEQ])  : $alns[0][S_SEQ];
        my $readQual = ($alns[0][S_FLAG] & _REVERSE) ? reverse($alns[0][S_QUAL]) : $alns[0][S_QUAL];
        my $pseudoRefSeq = getPseudoRefSeq(\@alns);
        print $readPathH join("\t", # print SV_READ_PATHS_FILE

            # read identifier and read-level metadata
            $alns[0][S_QNAME],
            $qLen,
            $alns[0][CH_TAG],
            $alns[0][READ_HAS_JXN],

            # concatenated alignment-level metadata
            join("\t", map {
                my $j = $_;
                join(",", map { 
                    my $x = $alns[$_][$j];
                    $j == S_FLAG and $x = ($x & _REVERSE) ? BOTTOM_STRAND : TOP_STRAND;
                    $x
                } 0..$#alns);
            } (S_RNAME, S_POS1, S_FLAG, S_MAPQ, DE_TAG, BLOCK_N, N_REF_BASES, ALN_FAILURE_FLAG, JXN_FAILURE_FLAG) ),

            # queryStart0_aln and queryEnd1_aln for each alignment in the path
            # establishes (potential) junction breakpoint in read coordinates
            # nReadBases_aln trivially calculated from here as queryEnd1 - queryStart0
            join(",", map { getQueryStart0(@{$alns[$_]}[S_FLAG, S_CIGAR]       ) } 0..$#alns),
            join(",", map { getQueryEnd1(  @{$alns[$_]}[S_FLAG, S_CIGAR], $qLen) } 0..$#alns),

            # additional alignment-level metadata
            # unlike SEQ/QUAL, CIGAR is NOT yet reordered into read coordinates for reverse-strand alignments
            join(",", map { $alns[$_][S_CIGAR] } 0..$#alns),

            # read SEQ and QUAL in original source read orientation (so could be bottom strand of genome)
            # this is different behavior than SV_JUNCTION_SOURCES_FILE
            $readSeq, 
            $readQual,

            # the corresponding reference sequence path to SEQ (again, could be bottom strand of genome)
            $pseudoRefSeq
        ), "\n";
    }

    # return path key for counting by shared script
    join("::",
        $alns[0][IS_END_TO_END],
        join(":", @distalNodes),
        join(":", @junctions),
        join(",", # site3
            $chromIndex{$alns[$#alns][S_RNAME]},
            $alns[$#alns][SEQ_SITE_INDEX1_2],
            ($alns[$#alns][S_FLAG] & _REVERSE) ? BOTTOM_STRAND : TOP_STRAND 
        )
    );
}

# reverse the process to convert counted hash keys to output formats
sub printIndexedVariant {
    my ($pathN, $count) = @_;

    # extract path metadata
    my @path = split("::", $varKey);
    my @site3 = split(",", $path[PATH_SITE3]);
    my $sitePos1_5 = $sites[$chromIndex1][$siteIndex1]; # site positions not yet adjusted back to fragment end on bottom strand
    my $sitePos1_3 = $sites[$site3[SITE3_CHROM_INDEX1]][$site3[SITE3_SITE_INDEX1]]; # unclear why this occassionally fails to find a site match
    my @distalNodes = map { [ split(",", $_) ] } split(":", $path[PATH_DISTAL_NODES]);
    my @junctionTypes;

    # save unique junctions with event counts and other metadata
    # suitable for merging to junction_sources for read recovery and ONT duplex purging
    unless($path[PATH_JUNCTIONS] eq NULL_ENTRY){
        my @junctions = split(":", $path[PATH_JUNCTIONS]);
        for(my $i = 0; $i < $#distalNodes; $i += 2){
            my @jxn = orientJunction($distalNodes[$i], $distalNodes[$i + 1], $junctions[$i / 2], \@junctionTypes, 1);
            print $uniqJxnH join("\t", # print SV_UNIQUE_JUNCTIONS_FILE
                @jxn[OJXN_CHROM_INDEX1_1..OJXN_JXN_TYPE],
                $count,
                @jxn[OJXN_ALN_OFFSET..OJXN_JXN_BASES],
                $pathN, 
                scalar(@junctions)     # the number of junctions in the path that carried this junction
            ), "\n";
        }

        # print middle, floating alignment(s) of multi-junction SV reads
        if(@junctions > 1){
            for(my $i = 1; $i < ($#distalNodes - 1); $i += 2){
                my $j = ($i - 1) / 2;
                print $distalAlnH join("\t",
                    $distalNodes[$i][NODE_CHROM_INDEX1],
                    $distalNodes[$i    ][NODE_REF_POS1], # refPos1_5, neither matches an RE site
                    $distalNodes[$i + 1][NODE_REF_POS1], # refPos1_2
                    0,                                   # refPos1_3, NA
                    $distalNodes[$i][NODE_STRAND_INDEX0],
                    join(",", @junctionTypes[$j, $j + 1]),
                    $pathN, 
                    scalar(@junctions),
                    (($i + 1) / 2) + 1,
                    $count
                ), "\n";
            }
        }

        # print last alignments of SV reads
        print $distalAlnH join("\t",
            $distalNodes[$#distalNodes - 1][NODE_CHROM_INDEX1],
            $distalNodes[$#distalNodes - 1][NODE_REF_POS1], # refPos1_5
            $distalNodes[$#distalNodes    ][NODE_REF_POS1], # refPos1_2
            $sitePos1_3 ?                                   # refPos1_3, may or may not match an RE site
                $sitePos1_3 - ($site3[SITE3_STRAND_INDEX0] == TOP_STRAND ? 1 : 0) : 
                0,
            $distalNodes[$#distalNodes - 1][NODE_STRAND_INDEX0],
            $junctionTypes[$#junctionTypes],
            $pathN, 
            scalar(@junctions),
            ($#distalNodes / 2) + 1,
            $count
        ), "\n";
    }

    # print first alignments of all reads (do last so that we have the junctionType leading out of an SV alignment)
    print $firstAlnH join("\t",
        $chromIndex1,
        $sitePos1_5 ? $sitePos1_5 - ($strandIndex0 == TOP_STRAND ? 0 : 1) : 1, # refPos1_5; always a fixed 5' RE refPos1 (not sitePos1...)
        $distalNodes[0][NODE_REF_POS1] || 0,                                   # refPos1_2, 3' end of first aln node2, may or may not match refPos1_3
        ($path[PATH_JUNCTIONS] eq NULL_ENTRY and $sitePos1_3) ?                # refPos1_3, actual or projected 3' RE refPos1 when no SV
            $sitePos1_3 - ($strandIndex0 == TOP_STRAND ? 1 : 0) :
            0, # do not retain read1 projection for SV reads; will plot as empty, not projected
        $strandIndex0,
        @junctionTypes ? $junctionTypes[0] : TYPE_PROPER,
        $pathN, 
        scalar(@junctionTypes),
        1,
        $count
    ), "\n";
}

# functions to describe paths
sub getJunction {
    my ($aln1, $aln2) = @_; # alignments to read 5' and 3' of a junction, respectively

    # cannot describe junction when SEQ was dropped upstream
    $$aln1[S_SEQ] eq NULL_ENTRY and return NULL_JUNCTION;

    # otherwise, determine the offset/overlap between the two alignments
    # alignmentOffset is positive for insertions, negative for microhomologies, 0 for blunt
    my $clip1 = 
        ($$aln1[S_FLAG] & _REVERSE) ? 
            getLeftClip( $$aln1[S_CIGAR]) :
            getRightClip($$aln1[S_CIGAR]);
    my $clip2 = 
        ($$aln2[S_FLAG] & _REVERSE) ? 
            getRightClip($$aln2[S_CIGAR]) :
            getLeftClip( $$aln2[S_CIGAR]);
    my $alignmentOffset = ($clip1 + $clip2) - $$aln1[INSERT_SIZE]; 

    # then determine the read bases corresponding to the insertion or microhomology
    # note that inserted bases must be provided by the read, not reference alignments
    # JXN_BASES leave in the orientation of the original read, thus,
    # will have two distinct rc'ed values when then same junction was sequenced in opposite orientations
    my $jxnBases = NULL_ENTRY; # *, a blunt joint
    # if(abs($alignmentOffset) > $MAX_JXN_BASES){
    #     $jxnBases = NULL_JXN_BASES; # large number of bases from platforms with low base accuracy are rarely useful and ~always have errors
    # } els
    if($alignmentOffset > 0){
        $jxnBases = ($$aln1[S_FLAG] & _REVERSE) ? 
            getRc( substr(substr($$aln1[S_SEQ], 0, $clip1), -$alignmentOffset) ) :
                   substr(substr($$aln1[S_SEQ], -$clip1), 0, $alignmentOffset);
    } elsif($alignmentOffset < 0) {
        $jxnBases = ($$aln1[S_FLAG] & _REVERSE) ? 
            getRc( substr(substr($$aln1[S_SEQ], 0, ($clip1 - $alignmentOffset)),   $alignmentOffset) ):
                   substr(substr($$aln1[S_SEQ], -($clip1 - $alignmentOffset)), 0, -$alignmentOffset);
    }
    join(",", $alignmentOffset, $jxnBases);
}

# enforce strict ordering of junction nodes for downstream junction aggregation
sub orientJunction {
    my ($node1, $node2, $junction, $junctionTypes, $isSplit) = @_;
    my @nodes = 
        $isSplit ? 
        (
            $node1,
            $node2
        ) : 
        (
            [ split(",", $node1) ],
            [ split(",", $node2) ]
        );
    my @junction = split(",", $junction);
    my $junctionType = getJunctionType(@nodes); # nodes before re-ordering
    $junctionTypes and push @$junctionTypes, $junctionType;

    # enforce strict ordering of junction pairs
    # translocations always sort low chromI to high chromI, i.e., by refPos1 along the composite genome
    # nearly all same-chrom junctions sort low refPos1 to high refPos1
    # only very rare inversions with identical refPos1 sort by strand, largely negligible
    # as a consequence, the canonical ordering of junctions is:
    #   deletions     sort to +/+, i.e., 1--->~~~2---> as canonical, <---2~~~<---1 gets flipped to it
    #                                        *   *                       *   *
    #   duplications  sort to -/-, i.e., <---1~~~<---2 as canonical, 2--->~~~1---> gets flipped to it
    #                                    *           *               *           *
    #   FF inversions sort to +/-, i.e., 1--->~~~<---2 as canonical, <---2~~~1---> gets flipped to it
    #                                        *       *                   *       *
    #   RR inversions sort to -/+, i.e., <---1~~~2---> as canonical, 2--->~~~<---1 gets flipped to it
    #                                    *       *                   *       *
    # the above patterns apply the same to translocations, where ~~|~~ simply crosses (a) chromosome boundary(ies)
    #     i.e., translocations follow either a del, dup, inv-FF or inv-RR pattern recognizable by oriented strand0 values
    # FF inversions can be viewed as "left anchored",  where read1 matches the reference genome orientation on the left side
    # RR inversions can be viewed as "right anchored", where read2 matches the reference genome orientation on the right side
    my @nodeI = sort { 
        $nodes[$a][NODE_CHROM_INDEX1]  <=> $nodes[$b][NODE_CHROM_INDEX1] or 
        $nodes[$a][NODE_REF_POS1]      <=> $nodes[$b][NODE_REF_POS1] or
        $nodes[$a][NODE_STRAND_INDEX0] <=> $nodes[$b][NODE_STRAND_INDEX0]
    } NODE1, NODE2;

    # when junction is re-oriented relative to source read ...
    if($nodeI[NODE1] == NODE2){ 
        # ... flip node strands
        $nodes[NODE1][NODE_STRAND_INDEX0] = (1 - $nodes[NODE1][NODE_STRAND_INDEX0]);
        $nodes[NODE2][NODE_STRAND_INDEX0] = (1 - $nodes[NODE2][NODE_STRAND_INDEX0]);
        # ... reverse complement junction bases
        # continuing above, now expect junctions sequenced in different orientations to have the same JXN_BASES in canonical read orientation
        rc(\$junction[JXN_JXN_BASES]);
        # note that S_SEQ/JXN_SEQ, i.e., the sequences of different reads matching the junction, are not rc'ed here
        # thus reads of multiply sequenced junctions may be in two different orientations as revealed by wasInverted
    }

    # return the ordered junction
    (
        @{$nodes[$nodeI[NODE1]]}, # ordered node1 = chrom pos strand
        @{$nodes[$nodeI[NODE2]]}, # ordered node2 = chrom pos strand
        $junctionType, 
        @junction,    # alnOffset jxnBases
        $nodeI[NODE1] # strandIndex0, i.e., wasInverted
    )
}
sub getJunctionType {
    my ($node1, $node2) = @_; # nodes before re-ordering
    $$node1[NODE_CHROM_INDEX1]  != $$node2[NODE_CHROM_INDEX1]  and return TYPE_TRANSLOCATION;
    $$node1[NODE_STRAND_INDEX0] != $$node2[NODE_STRAND_INDEX0] and return TYPE_INVERSION;
    if($$node1[NODE_STRAND_INDEX0] == TOP_STRAND){
        $$node1[NODE_REF_POS1]  <  $$node2[NODE_REF_POS1]      and return TYPE_DELETION;
    } else {
        $$node2[NODE_REF_POS1]  <  $$node1[NODE_REF_POS1]      and return TYPE_DELETION;
    }
    return TYPE_DUPLICATION;
}

# functions to describe paths
sub getRefPos1_5 {
    my ($aln) = @_;
    ($$aln[S_FLAG] & _REVERSE) ? 
        getEnd(@$aln[S_POS1, S_CIGAR]) :
        $$aln[S_POS1];
}
sub getNode1 {
    my ($aln) = @_;
    my $strandIndex0 = ($$aln[S_FLAG] & _REVERSE) ? BOTTOM_STRAND : TOP_STRAND;
    join(",", 
        $chromIndex{$$aln[S_RNAME]},
        $strandIndex0 == TOP_STRAND ? 
            $$aln[S_POS1] :
            getEnd(@$aln[S_POS1, S_CIGAR]),
        $strandIndex0
    )
}
sub getNode2 {
    my ($aln) = @_;
    my $strandIndex0 = ($$aln[S_FLAG] & _REVERSE) ? BOTTOM_STRAND : TOP_STRAND;
    join(",", 
        $chromIndex{$$aln[S_RNAME]},
        $strandIndex0 == TOP_STRAND ? 
            getEnd(@$aln[S_POS1, S_CIGAR]):
            $$aln[S_POS1],
        $strandIndex0
    )
}

# parse pseudo-reference sequence contig for one SV read across all alignments
sub getPseudoRefSeq {
    my ($alns) = @_;
    my $maxAlnsI = $#{$alns};
    join("", map { 
        my $i = $_;
        my $seq = getRefSeq2(
            $$alns[$i][S_RNAME], 
            $$alns[$i][S_POS1], 
            getEnd($$alns[$i][S_POS1], $$alns[$i][S_CIGAR]), 
            $$alns[$i][S_FLAG] & _REVERSE
        );
        if($i < $maxAlnsI){
            # must get junction anew, since we require analysis of even junctions filtered by BLOCK_N above
            my ($alignmentOffset, $jxnBases) = split(",", getJunction($$alns[$i], $$alns[$i + 1]));
            if($alignmentOffset < 0){ # microhomology bases contributed by aln2 for each junction, trimmed from aln1
                $seq = substr($seq, 0, length($seq) + $alignmentOffset);
            } elsif($alignmentOffset > 0) {
                $seq .= $jxnBases; # these and only these junction insertion bases in pseudo reference contig come from the read itself
            }
        }
        $seq
    } 0..$maxAlnsI);
}

# outer endpoint positions and ONT channels for duplicate purging
sub getOuterPos5 {
    my ($aln) = @_;
    my $strandIndex0 = ($$aln[S_FLAG] & _REVERSE) ? BOTTOM_STRAND : TOP_STRAND;
    $strandIndex0 == TOP_STRAND ? 
        $$aln[S_POS1] :
        getEnd(@$aln[S_POS1, S_CIGAR])
}
sub getOuterPos3 {
    my ($aln) = @_;
    my $strandIndex0 = ($$aln[S_FLAG] & _REVERSE) ? BOTTOM_STRAND : TOP_STRAND;
    $strandIndex0 == TOP_STRAND ? 
        getEnd(@$aln[S_POS1, S_CIGAR]) :
        $$aln[S_POS1]
}
sub getOuterEndpoints_ONT {
    my ($chromIndex1_5, $outerPos1_5, $chromIndex1_3, $outerPos1_3, $channel) = @_;
    my $oe1 = join("\t", $chromIndex1_5, $outerPos1_5);
    my $oe2 = join("\t", $chromIndex1_3, $outerPos1_3);
    ($oe1 cmp $oe2) <= 0 ? # yields the same key ordering for both strands
        (join("\t", $oe1, $oe2, $channel), 0) : # report whether we reordered endpoints
        (join("\t", $oe2, $oe1, $channel), 1);
}
sub getOuterEndpoints {
    my ($chromIndex1_5, $chromIndex1_3) = @_;
    $chromIndex1_5 <= $chromIndex1_3 ? # yields the same key ordering for both strands
        (join("\t", $chromIndex1_5, $chromIndex1_3), 0) : # report whether we reordered endpoints
        (join("\t", $chromIndex1_3, $chromIndex1_5), 1);
}

1;
