# actions:
#   prepare read alignments for downstream variant analysis
#     purge unmapped reads
#     order alignments across each read from 5' to 3'
#     repack SAM to SITE_SAM for streamlined parsing
#     match alignment nodes to RE filtering sites, record in SITE_INDEX1_1 to SITE_DIST_2
#     discard sequences where one or both complete outer nodes fail to match an RE filtering site
#     project the 3' end of read alignments to the next RE site, record in SEQ_SITE_INDEX1_2 to IS_END_TO_END
#     assess whether insert size/stem length is within the allowed range, record in INSERT_SIZE to PASSED_STEM3
#     calculate the traversal delta over all sets of read alignments (across all sets of junctions) to set BLOCK_N
#         used to suppress spurious junctions arising in low quality regions with ~equal inserted and deleted bases
#     enforce alignment-level quality filtering to set ALN_FAILURE_FLAG
#         used to suppress untrusted junctions arising from aligner issues
#     flag chimeric junctions, in JXN_FAILURE_FLAG, at SV breakpoint nodes that match (discard distal/3' portion):
#         - RE sites (due to intermolecular ligation)
#         - foldback inversions (due to ONT duplex reads or inversion synthesis)
#         - low quality insertions (ONT only, to suppress follow-on chimeras)
#         - adapter insertions (due to any process that conjoins reads across an adapter)
#     assess the on-target status of reads, recorded in TARGET_CLASS and END5_ON_TARGET
#     flag reads that contain junctions that passed and junction quality filters to set READ_HAS_JXN
# input:
#   NAME_BAM_FILE, as generated by `align` step 
#   CLOSEST_SITE_BINARY_FILE and others created by 'locate' step
#   config parameters:
#       ACCEPT_ENDPOINT_DISTANCE, stricter, for RE outer endpoints
#       REJECT_JUNCTION_DISTANCE, more permissive, thus rejects end-to-end chimeras more easily
#       etc.
# output:
#   SITE_SAM written to chromosome-level files in SITE_SAM_DIR, where:
#      each row is one alignment, like SAM
#      each read's alignments are in query order from 5' to 3'
#      error correction fields are set as above
#      all alignments (from all validated RE fragments) are still present
#          even those that had alignment or junction-level failure flags set to support filtering downstream
#          except that inserts that don't match expected RE fragments at outer endpoints are discarded

# variables
export APPLY_FILTERS_DIR=${ACTION_DIR}/apply_filters
UNMAPPED=4

# load the site lookup binaries into /dev/shm for fastest scanning
# production
echo "copying $ENZYME_NAME site lookup files to ram disk"
cp $CLOSEST_SITE_BINARY_FILE $TMP_DIR_WRK_SHM
cp $SITE_DATA_BINARY_FILE    $TMP_DIR_WRK_SHM
export CLOSEST_SITE_LOOKUP_WRK=$TMP_DIR_WRK_SHM/`basename $CLOSEST_SITE_BINARY_FILE`
export SITE_DATA_LOOKUP_WRK=$TMP_DIR_WRK_SHM/`basename $SITE_DATA_BINARY_FILE`
# # debugging
# export CLOSEST_SITE_LOOKUP_WRK=$CLOSEST_SITE_BINARY_FILE
# export SITE_DATA_LOOKUP_WRK=$SITE_DATA_BINARY_FILE
echo "parsing alignments to quality-filtered, RE-matched, error-corrected fragments and reads"

# purge unmapped reads/empty alignments and convert to SAM
samtools view --threads $SAMTOOLS_CPU --exclude-flags $UNMAPPED $NAME_BAM_FILE | 

###################
# head -n 50000 | 

# apply error correction and flagging steps
# print SITE_SAM to chromosome-level file in preparation for variant analysis
perl ${APPLY_FILTERS_DIR}/apply_filters.pl

# # working per event:
# #   PENDING: enforce zoo rejection
# #   order alignments across each read from 5' to 3'
# #   repack SAM to SITE_SAM for streamlined parsing
# #   record number of aligned read bases and associated ref span
# #   record whether insert size/stem length is within the allowed range
# perl ${MATCH_DIR}/order_alignments.pl |

# # working per read:
# #   calculate the reference vs. read traversal delta between all sets of alignments (across all sets of junctions)
# #   use calculated deltas and MIN_TRAVERSAL_DELTA to set BLOCK_N of all alignments
# #   junctions between alignments with the same BLOCK_N may be considered artifactual during SV analysis
# #   block numbering is done before alignment quality truncation when all read alignments are still present
# #   SVs that fail block traversal checks may or may not be split by downstream quality filters
# perl ${MATCH_DIR}/check_traversal_delta.pl | 

# # working per sequence:
# #   record whether alignments pass alignment-level quality filters
# perl ${MATCH_DIR}/enforce_quality_filters.pl |

# # working per alignment:
# #   find the nearest filtering RE site to each alignment node and the direction to it
# perl ${MATCH_DIR}/match_nodes_to_sites.pl |

# # working per sequence:
# #   reject and discard sequences that don't match RE sites at complete outermost endpoints
# #       disregard incomplete 3' ends when applying this filter
# #   fill the sequence 3' site fields end when already known for end-to-end/complete sequences with no SV
# perl ${MATCH_DIR}/discard_unmatched_sequences.pl | 

# # working per read:
# #   flag alignment proximal to SV junctions that match RE sites or are otherwise identified as end-to-end chimeras
# #   in particular, reads are also processed for adapter presence, ONT follow-ons, and foldback inversions
# perl ${MATCH_DIR}/split_chimeric_reads.pl | 

# # working per read:
# #   when not set above, project the 3' end of required alignments to the next RE site
# #   assess the proper fragment insert size distribution
# #   assess whether alignment/read ends matched a target region, if TARGETS_BED provided
# #   print SITE_SAM to chromosome-level file in preparation for variant analysis
# perl ${MATCH_DIR}/project_incomplete_reads.pl
