# actions:
#   prepare read alignments for downstream variant analysis
#     purge unmapped reads
#     split unmerged read pairs for downstream processing as single-end reads
#     order alignments across each read from 5' to 3'
#     repack SAM to SITE_SAM for streamlined parsing
#     when applicable to RE fragment libraries:
#         match alignment nodes to RE filtering sites, record in SITE_INDEX1_1 to SITE_DIST_2
#         discard sequences where one or both complete outer nodes fail to match an RE filtering site
#         project the 3' end of read alignments to the next RE site, record in SEQ_SITE_INDEX1_2 to IS_END_TO_END
#     when applicable to size-selected libraries:
#         assess whether insert size/stem length is within the allowed range, record in INSERT_SIZE to PASSED_STEM3
#     calculate the traversal delta over all sets of read alignments (across all sets of junctions) to set BLOCK_N
#         used to suppress spurious junctions arising in low quality regions with ~equal inserted and deleted bases
#     enforce alignment-level quality filtering to set ALN_FAILURE_FLAG
#         used to suppress untrusted junctions arising from aligner issues
#     flag chimeric junctions, in JXN_FAILURE_FLAG, at SV breakpoint nodes that match (discard distal/3' portion):
#         - RE sites (due to intermolecular ligation, when applicable)
#         - foldback inversions (due to ONT duplex reads or inversion synthesis)
#         - low quality insertions (ONT only, to suppress follow-on chimeras)
#         - adapter insertions (due to any process that conjoins reads across an adapter)
#     when applicable to targeted libraries:
#         assess whether alignment/read ends matched a target region, record in TARGET_MATCH_FLAG
#     flag reads that contain junctions that passed and junction quality filters to set READ_HAS_JXN
# input:
#   NAME_BAM_FILE, as generated by `align` step 
#   CLOSEST_SITE_BINARY_FILE and others created by 'locate' step
#   config parameters:
#       ACCEPT_ENDPOINT_DISTANCE, stricter, for RE outer endpoints
#       REJECT_JUNCTION_DISTANCE, more permissive, thus rejects end-to-end chimeras more easily
#       etc.
# output:
#   SITE_SAM written to chromosome-level files in SITE_SAM_DIR, where:
#      each row is one alignment, like SAM
#      each read's alignments are in query order from 5' to 3'
#      unmerged paired reads are suffixed with /1 or /2 in QNAME for independent processing downstream
#      error correction fields are set as above
#      all alignments (from all validated RE fragments) are still present
#          even those that had alignment or junction-level failure flags set to support filtering downstream
#          except that inserts that don't match expected RE fragments at outer endpoints are discarded

# variables
export APPLY_FILTERS_DIR=${ACTION_DIR}/apply_filters
UNMAPPED=4
MATE_UNMAPPED=8
ANY_UNMAPPED=12

# load the site lookup binaries into /dev/shm for fastest scanning
export CLOSEST_SITE_LOOKUP_WRK=NA
export SITE_DATA_LOOKUP_WRK=NA
if [ "$REJECTING_JUNCTION_RE_SITES" = "TRUE" ]; then
    # production
    echo "copying $ENZYME_NAME site lookup files to ram disk"
    cp $CLOSEST_SITE_BINARY_FILE $TMP_DIR_WRK_SHM
    cp $SITE_DATA_BINARY_FILE    $TMP_DIR_WRK_SHM
    export CLOSEST_SITE_LOOKUP_WRK=$TMP_DIR_WRK_SHM/`basename $CLOSEST_SITE_BINARY_FILE`
    export SITE_DATA_LOOKUP_WRK=$TMP_DIR_WRK_SHM/`basename $SITE_DATA_BINARY_FILE`
    # # debugging
    # export CLOSEST_SITE_LOOKUP_WRK=$CLOSEST_SITE_BINARY_FILE
    # export SITE_DATA_LOOKUP_WRK=$SITE_DATA_BINARY_FILE
fi

# purge unmapped reads/empty alignments and convert to SAM
# both reads of a pair must be aligned for an insert to be considered
echo "parsing alignments to quality-filtered, RE-matched, error-corrected fragments and reads"
samtools view --threads $SAMTOOLS_CPU --exclude-flags $ANY_UNMAPPED $NAME_BAM_FILE | 

###################
# head -n 50000 | 

# apply error correction and flagging steps
# print SITE_SAM to chromosome-level file in preparation for variant analysis
perl ${APPLY_FILTERS_DIR}/apply_filters.pl
