use strict;
use warnings;

# scope:
#   this script is applied to non-RE-cleaved fragments, i.e., a non-ligFree library,
#   to skip non-applicable actions/index levels in the regular index_fragments.pl
# action:
#   describe the SV paths of all reads
#   use a fragment index to count unique paths
#   work is parallelized by chromosome for speed gains and sorting efficiency
#   this script is applicable to all sequencing platforms
#   SV paths are described by:
#       refPos1_5 = the 5'-most fragment coordinate plus clipping on the indexed chrom/strand
#       isEndToEnd = 0|1 indicating whether refPos1_3 represents the end of the sequenced insert
#           when isEndToEnd == 1 for an unpaired read, the last distalNode is redundant with refPos1_3
#       distalNodes = a colon-delimited list of more distal/3' nodes (just the 3'-most node if no SV in read)
#       junctions = a colon-delimited list of SV junctions between the nodes ("*" if no SV in read)
#       refPos1_3 = the 3'-most fragment coordinate plus clipping on the chromosome of the last alignment/distal node
#       readHasSv = 0|1 indicating whether this read retained a SV AFTER haplotype adjustment by `align genotype`
#   where paths are indexed as:
#       chromIndex1,refPos1_5,strandIndex0, where
#           chromIndex1  = 1-based index of ordered chromosomes
#           strandIndex0 = 0 for top strand, 1 for bottom strand sequence
#   a distal/3' junction node is described as:
#       chromIndex1,refPos1,strandIndex0, where
#           refPos1 = 1-based coordinate of the last aligned base in the chromosome
#   and an SV junction is described by read-dependent properties that can't be derived from nodes:
#       alignmentOffset,jxnBases, where
#           alignmentOffset = number of non-reference bases found at junction (negative if microhomology)
#           jxnBases = the inserted or microhomologous bases (omitted for long ONT sequences)
#   junctions were already split upstream at low quality alignments and chimeras
#   junctions and associated distal nodes are omitted here, as if they didn't exist,
#       when blockN of the two flanking alignments is the same, i.e., the junction failed traversalDelta checks
#       since the most likely true path was contiguous across that (portion of the) read
#   a hash is used to track the unique paths encountered for each unique 5' end as:
#       isEndToEnd::distalNodes::junctions::refPos1_3::readHasSv::matchingHaps
#   indexing occurs with respect to read strand, so reads are NOT aggregated by strand
#       i.e., a variant sequenced in two strand orientations will be found on at least two indexed lines
#       no such strand aggregation is performed downstream since:
#           overlapping paired reads were previously merged to prevent redundancy in the overlap region
#           two single-end reads rarely arise from two strands of the same source duplex
#       thus, the potential for non-independent variant calls on two strands is considered small
#       however, multiple independent indexed lines may exist for a clonal variant if sequencing errors give distinct hash keys
#   indexing is an aggregating action, so read/event identifiers are lost in the index
#   to allow indexed SV paths to be correlated back to source reads, especially for ONT duplex purging
#       a list is saved of all pre-aggregation SV paths with their associated QNAME and ONT channel
#       as with the index, different paths in the list may be non-identical but with the same SV due to sequencing errors
# input:
#   SITE_SAM files generated by `analyze fragments`, one file per chromosome
# output:
#   alignment-level files, with event counts, used for generating fragment maps:
#       FIRST_ALIGNMENTS    = the single alignment at the 5' end of a read
#                               sorted by coordinate by this script
#       DISTAL_ALIGNMENTS   = the alignment(s) after SV junction(s) in the read
#                               sorted by coordinate after downstream aggregation to genome-level files
#                               last distal alignment carries information on the distance from refPos1_2 to refPos1_3
#           all alignment files carry information on three nodes (even if empty==0)
#               refPos1_5 = the 5'-most base in the alignment (node1)
#               refPos1_2 = the 3'-most base in the alignment (node2)
#               refPos1_3 = the 3'-most base in the RE fragment (0 if not known, not applicable, not projected)
#           alignment nodes are in 5' to 3' order on the read, i.e., refPos1_5 is > refPos1_2 when strandIndex0 == 1
#   junction-level files, used for establishing SV uniqueness and zygosity:
#       JUNCTION_SOURCES    = one line per pre-aggregation junction with source QNAME and ONT channel
#       UNIQUE_JUNCTIONS    = one line per post-aggregation junction with event counts
#           junction nodes are sorted such that:
#               SVs encountered on different strands have the same node1 and node2 order
#               column strandIndex0 indicates the source strand/orientation, i.e., is true==1 when flipped relative to the read
#           junction nodes are not yet aggregated for fuzzy-logic proximity matching or ONT duplex purging
#   note that :
#       most alignments are in FIRST_ALIGNMENTS on all platforms
#       DISTAL_ALIGNMENTS all come from SV molecules
#   all output files are, at least initially, one file per _indexing_ chromosome
#       only entries in FIRST_ALIGNMENTS are guaranteed to reside on the indexing chromosome
#       all other files are aggregated into coordinate-sorted genome-level files in the next action step

# initialize reporting
our $script = "index_fragments";
our $error  = "$script error";

# working variables
use vars qw(
    %chromIndex @matchingHaps
    $jxnSrcH $uniqJxnH $firstAlnH $distalAlnH $alnSizeH $readPathH
    $chrom $chromIndex1 $paddedChromIndex1
    @alns @index $refPos1_5
    $varKey
);

# load dependencies
my $perlUtilDir = "$ENV{MODULES_DIR}/utilities/perl";
map { require "$perlUtilDir/$_.pl" } qw(workflow);

# environment variables
fillEnvVar(\our $MAX_JXN_BASES,           'MAX_JXN_BASES');
fillEnvVar(\our $SAMPLE_PATHS_PREFIX_WRK, 'SAMPLE_PATHS_PREFIX_WRK');
fillEnvVar(\my $SEQUENCING_PLATFORM,      'SEQUENCING_PLATFORM');
my $isONT = ($SEQUENCING_PLATFORM eq "ONT");

# constants
use constant {
    S_QNAME             => 0, # SITE_SAM fields
    S_FLAG              => 1,
    S_RNAME             => 2,
    S_POS1              => 3, # 1-based
    S_MAPQ              => 4,
    S_CIGAR             => 5,
    DE_TAG              => 6,
    CS_TAG              => 7,
    XF_TAG              => 8,
    XH_TAG              => 9,
    N_REF_BASES         => 10,
    N_READ_BASES        => 11,
    BLOCK_N             => 12,
    SITE_INDEX1_1       => 13,
    SITE_POS1_1         => 14,
    SITE_HAPS_1         => 15,
    SITE_DIST_1         => 16,
    SITE_INDEX1_2       => 17,
    SITE_POS1_2         => 18,
    SITE_HAPS_2         => 19,
    SITE_DIST_2         => 20,
    SEQ_SITE_INDEX1_2   => 21,
    SEQ_SITE_POS1_2     => 22,
    SEQ_SITE_HAPS_2     => 23,
    IS_END_TO_END       => 24,
    READ_HAS_JXN        => 25,
    TARGET_CLASS        => 26,
    S_SEQ               => 27,
    S_QUAL              => 28,
    #-------------
    _IS_PAIRED      => 1,  # SAM FLAG bits
    _PROPER_PAIR    => 2,
    _UNMAPPED       => 4,
    _MATE_UNMAPPED  => 8,
    _REVERSE        => 16,
    _MATE_REVERSE   => 32,
    _FIRST_IN_PAIR  => 64,
    _SECOND_IN_PAIR => 128,
    _SECONDARY      => 256,
    _FAILED_QC      => 512,
    _DUPLICATE      => 1024,
    _SUPPLEMENTAL   => 2048,
    #-------------
    channel             => 0, # incoming qName extensions
    trim5               => 1,
    trim3               => 2,
    isMerged            => 3, # true=2 for legacy reasons
    nRead1              => 4,
    nRead2              => 5,
    splitGapReadN       => 6,
    readN               => 7,
    N_QNAME_EXTENSIONS  => 8,
    #-------------
    FALSE  => 0,
    TRUE   => 1,
    #-------------
    TOP_STRAND    => 0,
    BOTTOM_STRAND => 1,
    #-------------
    ALN_HAS_SNV         => 1, # variant flag bits
    READ_HAS_SNV        => 2,
    READ_HAS_SV         => 4,
    EVENT_HAS_SNV       => 8,
    EVENT_HAS_SV        => 16,
    EVENT_HAS_VARIANT   => 32,
    #-------------
    NULL_ENTRY      => "*",
    NULL_JUNCTION   => "*,*",
    NULL_JXN_BASES  => "#", # the value used when junction bases were not processed, but alignment offset is present
    #-------------
    PATH_REF_POS1_5       => 0,
    PATH_STRAND_INDEX0    => 1,
    PATH_IS_END_TO_END    => 2,
    PATH_DISTAL_NODES     => 3,
    PATH_JUNCTIONS        => 4,
    PATH_READ_HAS_SV      => 5,
    PATH_HAPLOTYPES       => 6,
    #-------------
    NODE_CHROM_INDEX1   => 0,
    NODE_REF_POS1       => 1,
    NODE_STRAND_INDEX0  => 2,
    #-------------
    TYPE_PROPER         => 0, # junction/edge types
    TYPE_DELETION       => 1,
    TYPE_DUPLICATION    => 2,
    TYPE_INVERSION      => 3,
    TYPE_TRANSLOCATION  => 4,
    #-------------
    OJXN_CHROM_INDEX1_1     => 0,
    OJXN_REF_POS1_1         => 1,
    OJXN_STRAND_INDEX0_1    => 2,
    OJXN_CHROM_INDEX1_2     => 3,
    OJXN_REF_POS1_2         => 4,
    OJXN_STRAND_INDEX0_2    => 5,
    OJXN_JXN_TYPE           => 6,
    OJXN_ALN_OFFSET         => 7,
    OJXN_JXN_BASES          => 8,
    OJXN_ORIENTATION        => 9,
};

# create a hash key for a read and count it in the index
sub indexRead {

    # collect the unstranded outer endpoints for PCR duplicate/ONT duplex purging
    # including ONT channel allows duplicates sequenced in different channels to persist
    # known limitation: does not use fuzzy matching on non-RE outer endpoints
    my $channel = $isONT ? getONTChannel($alns[0]) : 0;
    my ($outerEndpoints, $isReordered) = getOuterEndpoints(
        $chromIndex1,                        getOuterPos5($alns[0]),
        $chromIndex{$alns[$#alns][S_RNAME]}, getOuterPos3($alns[$#alns]),
        $channel
    );

    # print alignment sizes for library deduplication and summation downstream
    foreach my $alnI0(0..$#alns){
        print $alnSizeH join("\t", 
            $outerEndpoints, # chromIndex1_1, siteIndex1_1, chromIndex1_2, siteIndex1_2, channel
            $isReordered ? ($#alns - $alnI0) : $alnI0, # (reordered) alnI0
            $alns[$alnI0][N_REF_BASES], 
            $alns[$alnI0][N_READ_BASES]
        ), "\n";
    }

    # assemble the parts of the SV path key
    my (@distalNodes, @junctions);
    if(@alns > 1){
        foreach my $i(1..$#alns){ # internal nodes and junctions
            unless($alns[$i - 1][BLOCK_N] == $alns[$i][BLOCK_N]){
                push @distalNodes, getNode2($alns[$i - 1]);
                push @distalNodes, getNode1($alns[$i]);
                push @junctions, getJunction($alns[$i - 1], $alns[$i]);
            }
        }
    }
    push @distalNodes, getNode2($alns[$#alns]);
    @junctions or @junctions = (NULL_ENTRY);

    # save junction sources with QNAME, ONT channel and other event metadata for ONT duplex purging and other needs
    unless($junctions[0] eq NULL_ENTRY){
        $outerEndpoints =~ s/\t/:/g;
        for(my $i = 0; $i < $#distalNodes; $i += 2){
            my $aln1I = $i / 2;
            my $seqI = $alns[$aln1I][S_SEQ] eq "*" ? $aln1I + 1 : $aln1I; # obsolete? SEQ and QUAL no longer masked on SV reads

            # replace commas in fields that must be concatenated downstream
            # this includes by bedtools groupby, which only offers comma delimiters
            # S_QNAME, CH_TAG, S_SEQ, S_CIGAR, S_MAPQ, and DE_TAG are comma-safe as is
            # MM_TAG, ML_TAG_BRDU, and ML_TAG_EDU were changed by analyze/fragments to use colon delimiters
            $alns[$seqI][S_QUAL] =~ s/,/+/g; # one value poorer quality than comma on the ASCII table

            print $jxnSrcH join("\t", # print SV_JUNCTION_SOURCES_FILE

                # these values describe the junction itself
                # chrom1,pos1,strand1,chrom2,pos2,strand2,jxnType,alnOffset,jxnBases,wasInverted
                orientJunction($distalNodes[$i], $distalNodes[$i + 1], $junctions[$i / 2]),

                # these values are the same for all read alignments (even those not flanking the junction)
                $alns[0][S_QNAME],
                $channel,
                $outerEndpoints, # ordered outer endpoints for duplicate purging

                # these values aggregate the two flanking alignments to a single statistic
                min( $alns[$aln1I][S_MAPQ], $alns[$aln1I + 1][S_MAPQ]),
                max( $alns[$aln1I][DE_TAG], $alns[$aln1I + 1][DE_TAG]),
                0, # unsigned shortest distance to a site, NA

                # these values are shared by the flanking alignments
                # we do not duplicate SEQ and QUAL as it is the same for the alignments
                # but recognize that SEQ and QUAL may be reverse complemented for aln2 relative to aln1,
                # where SEQ and QUAL are provided in aln1 orientation
                # importantly, unlike readPaths, SEQ and QUAL are reference, not read, oriented
                #    i.e. they always match the reference genome sequence and may be rc'ed relative to the read
                # need strandIndex0 and wasInverted to interpret SEQ and QUAL orientation
                $alns[$seqI][S_SEQ],
                $alns[$seqI][S_QUAL],

                # these values concatenate pairs of alignment-level properties of the two flanking alignments
                # use double-colon to separate instances (to retain potential for colon-delimited alignment tags in the future)
                join("::", $alns[$aln1I][S_CIGAR], $alns[$aln1I + 1][S_CIGAR])
            ), "\n"; 
        }


        # print the path of each read as a concatenated reference sequence across all read junctions
        # used for read-level visualization
        my $qLen = length($alns[0][S_SEQ]);
        my $readSeq  = ($alns[0][S_FLAG] & _REVERSE) ?   getRc($alns[0][S_SEQ])  : $alns[0][S_SEQ];
        my $readQual = ($alns[0][S_FLAG] & _REVERSE) ? reverse($alns[0][S_QUAL]) : $alns[0][S_QUAL];
        my $pseudoRefSeq = getPseudoRefSeq(\@alns);
        print $readPathH join("\t", # print SV_READ_PATHS_FILE

            # read identifier and read-level metadata
            $alns[0][S_QNAME],
            $qLen,
            $channel,
            $alns[0][READ_HAS_JXN],

            # concatenated alignment-level metadata
            join("\t", map {
                my $j = $_;
                join(",", map { 
                    my $x = $alns[$_][$j];
                    $j == S_FLAG and $x = ($x & _REVERSE) ? BOTTOM_STRAND : TOP_STRAND;
                    $x
                } 0..$#alns);
            } (S_RNAME, S_POS1, S_FLAG, S_MAPQ, DE_TAG, BLOCK_N, N_REF_BASES) ),

            # queryStart0_aln and queryEnd1_aln for each alignment in the path
            # establishes (potential) junction breakpoint in read coordinates
            # nReadBases_aln trivially calculated from here as queryEnd1 - queryStart0
            join(",", map { getQueryStart0(@{$alns[$_]}[S_FLAG, S_CIGAR]       ) } 0..$#alns),
            join(",", map { getQueryEnd1(  @{$alns[$_]}[S_FLAG, S_CIGAR], $qLen) } 0..$#alns),

            # additional alignment-level metadata
            # unlike SEQ/QUAL, CIGAR is NOT yet reordered into read coordinates for reverse-strand alignments
            join(",", map { $alns[$_][S_CIGAR] } 0..$#alns),

            # read SEQ and QUAL in original source read orientation (so could be bottom strand of genome)
            # this is different behavior than SV_JUNCTION_SOURCES_FILE
            $readSeq, 
            $readQual,

            # the corresponding reference sequence path to SEQ (again, could be bottom strand of genome)
            $pseudoRefSeq
        ), "\n";
    }

    # return path key for counting by shared script
    join("::",
        sprintf("%09d", $refPos1_5), # zero pad refPos1_5 up to 999,999,999 for index bin lexical sorting
        ($alns[0][S_FLAG] & _REVERSE) ? BOTTOM_STRAND : TOP_STRAND,
        $alns[0][IS_END_TO_END],
        join(":", @distalNodes),
        join(":", @junctions),
        ($alns[0][XF_TAG] & READ_HAS_SV) ? TRUE : FALSE, # TRUE is there was still an SV present in a best haplotype or reference alignment
        join(",",                                        # even if a subset of path SVs matched a haplotype; FALSE if a full path aligned contiguously to a haplotype
            $matchingHaps[$alns[0][XH_TAG]],
            @alns == 1 ?   # aln2 haplotype as needed
                () : 
                ($matchingHaps[$alns[$#alns][XH_TAG]])
        )
    );
}

# reverse the process to convert counted hash keys to output formats
sub printIndexedVariant {
    my ($pathN, $count) = @_;

    # extract path metadata
    my @path = split("::", $varKey);
    my @distalNodes = map { [ split(",", $_) ] } split(":", $path[PATH_DISTAL_NODES]);
    my @junctionTypes;
    my @haplotypes = split(",", $path[PATH_HAPLOTYPES]);

    # save unique junctions with event counts and other metadata
    # suitable for merging to junction_sources for read recovery and ONT duplex purging
    unless($path[PATH_JUNCTIONS] eq NULL_ENTRY){
        my @junctions = split(":", $path[PATH_JUNCTIONS]);
        for(my $i = 0; $i < $#distalNodes; $i += 2){
            my @jxn = orientJunction($distalNodes[$i], $distalNodes[$i + 1], $junctions[$i / 2], \@junctionTypes, 1);
            print $uniqJxnH join("\t", # print SV_UNIQUE_JUNCTIONS_FILE
                @jxn[OJXN_CHROM_INDEX1_1..OJXN_JXN_TYPE],
                $count,
                @jxn[OJXN_ALN_OFFSET..OJXN_JXN_BASES],
                $pathN, 
                scalar(@junctions),     # the number of junctions in the path that carried this junction
                $path[PATH_READ_HAS_SV] # TRUE if _any_ junction in this path was unknown to reference[+genotype] (not necessarily this junction)
            ), "\n";                    # FALSE if this path aligned contiguously to a haplotype, which means this is an expected SV junction
        }

        # print middle, floating alignment(s) of multi-junction SV reads
        if(@junctions > 1){
            for(my $i = 1; $i < ($#distalNodes - 1); $i += 2){
                my $j = ($i - 1) / 2;
                print $distalAlnH join("\t",
                    $distalNodes[$i][NODE_CHROM_INDEX1],
                    $distalNodes[$i    ][NODE_REF_POS1], # refPos1_5, neither matches an RE site
                    $distalNodes[$i + 1][NODE_REF_POS1], # refPos1_2
                    0,                                   # refPos1_3, NA
                    $distalNodes[$i][NODE_STRAND_INDEX0],
                    join(",", @junctionTypes[$j, $j + 1]),
                    0, # cannot determine best haplotypes of a floating alignment
                    $pathN, 
                    scalar(@junctions),
                    (($i + 1) / 2) + 1,
                    $path[PATH_READ_HAS_SV],
                    $count
                ), "\n";
            }
        }

        # print last alignments of SV reads
        my $refPos1_2 = $distalNodes[$#distalNodes][NODE_REF_POS1];
        print $distalAlnH join("\t",
            $distalNodes[$#distalNodes - 1][NODE_CHROM_INDEX1],
            $distalNodes[$#distalNodes - 1][NODE_REF_POS1], # refPos1_5
            $refPos1_2,                                     # refPos1_2
            $refPos1_2,                                     # refPos1_3, same as refPos1_2 for non-RE fragments, i.e., never projected
            $distalNodes[$#distalNodes - 1][NODE_STRAND_INDEX0],
            $junctionTypes[$#junctionTypes],
            $haplotypes[1],
            $pathN, 
            scalar(@junctions),
            ($#distalNodes / 2) + 1,
            $path[PATH_READ_HAS_SV],
            $count
        ), "\n";
    }

    # print first alignments of all reads (do last so that we have the junctionType leading out of an SV alignment)
    my $refPos1_2 = $distalNodes[0][NODE_REF_POS1];
    print $firstAlnH join("\t",
        $chromIndex1,
        $path[PATH_REF_POS1_5] + 0,                            # refPos1_5, 5' end of first aln node1
        $refPos1_2,                                            # refPos1_2, 3' end of first aln node2, may or may not match refPos1_3
        $path[PATH_JUNCTIONS] eq NULL_ENTRY ? $refPos1_2 : 0,  # refPos1_3, actual or projected 3' RE refPos1 when no SV
        $path[PATH_STRAND_INDEX0],
        @junctionTypes ? $junctionTypes[0] : TYPE_PROPER,
        $haplotypes[0],
        $pathN, 
        scalar(@junctionTypes),
        1,
        $path[PATH_READ_HAS_SV],
        $count
    ), "\n";
}

# report quality metrics
sub reportFinalMetadata_all_thread_chroms {
    # do nothing yet
}

# do the work
require "$ENV{PIPELINE_SHARED_DIR}/non_RE/index_fragments.pl";
