# action:
#     set environment variables that indicate the type of library being analyzed
#     set environment variables with output file paths and names
# requires:
#     source $MODULES_DIR/genome/set_genome_vars.sh
#     source ${MODULES_DIR}/genotype/set_genotype_vars.sh (genotype only)
#     source $MODULES_DIR/REs/set_re_vars.sh
# usage:
#     source $MODULES_DIR/agFree/set_agFree_vars.sh

# library/sample output files
export LIBRARY_STATS_FILE=${DATA_FILE_PREFIX}.library_stats.yml

# set alignment and other analysis parameters based on the sequencing platform in use
# for clarity, these options are read from a table
if [ "$SEQUENCING_PLATFORM" != "" ]; then
    source <( perl ${MODULES_DIR}/agFree/set_platform_vars.pl )
    if [ "$GET_CONFIGURATION_ERROR" != "" ]; then
        echo
        echo $GET_CONFIGURATION_ERROR
        echo
        exit 1
    fi
fi

# set alignment and other analysis parameters based on the library preparation type in use
# for clarity, these options are read from a table
if [ "$LIBRARY_TYPE" != "" ]; then
    source <( perl ${MODULES_DIR}/agFree/set_library_type_vars.pl )
    if [ "$GET_CONFIGURATION_ERROR" != "" ]; then
        echo
        echo $GET_CONFIGURATION_ERROR
        echo
        exit 1
    fi
fi

# set the variable pointers to the reference GENOME or GENOTYPE in use, called the XGENOME
export XGENOME=${GENOME}
export DATA_XGENOME_PREFIX=${DATA_GENOME_PREFIX}
if [ "$USING_GENOTYPE" == "TRUE" ]; then
    export XGENOME=${GENOTYPE}
    export DATA_XGENOME_PREFIX=${DATA_GENOTYPE_PREFIX}
fi
export DATA_XGENOME_RE_PREFIX=${DATA_XGENOME_PREFIX}.${ENZYME_NAME}

# file of aligned read endpoints, BEFORE aggregating by sample or reference site matches
# these endpoints arise from one or more samples considered to represent the same genotype+RE
# these are the files generated by locate extract_endpoints
#   it is best practice for DATA_NAME to be set as <GENOTYPE>_<RE> when running the locate pipeline
#   do not add GENOTYPE or RE to site file names as a sites directory is expected to represent one genotype+RE
export OBSERVED_ENDPOINTS_FILE=${DATA_XGENOME_PREFIX}.read_endpoints.txt.gz

# files of read endpoints and filtering RE sites, AFTER aggregating by sample or reference site matches
# these are the files generated by locate tabulate_endpoints and create_index
# they are genotype+RE+reference, not sample, specific
# and thus don't need to be created anew for every sample once a stable site list exists
# these are the paths as used by locate
# `genotype digest` and `genome index` set override to place output indices into resources directory, not TASK_DIR
export APP_ENDPOINTS_FILE=${DATA_XGENOME_PREFIX}.read_endpoints.rds
if [ "$REFERENCE_SITES_PREFIX" != "" ]; then # as used by `genotype digest` and `genome index`
    INDEXED_SITES_PREFIX=${REFERENCE_SITES_PREFIX}.filtering_sites
else # as used by `locate``
    INDEXED_SITES_PREFIX=${DATA_XGENOME_PREFIX}.filtering_sites
fi
export FILTERING_SITES_FILE=${INDEXED_SITES_PREFIX}.txt.gz
export FILTERING_SITES_BGZ=${INDEXED_SITES_PREFIX}.txt.bgz
export SITE_CHROM_DATA_FILE=${INDEXED_SITES_PREFIX}.index.txt        # tabular index to next three files
export CLOSEST_SITE_BINARY_FILE=${INDEXED_SITES_PREFIX}.closest_site # one value per genome position = signed closest site index
export SITE_DATA_BINARY_FILE=${INDEXED_SITES_PREFIX}.site_data       # one value pair per RE filtering site = sitePos1 on chrom and matching haplotypes

# index/lookup files matching the previous set, with paths as specified in sample-specific jobs by option --re-sites-dir
if [ "$RE_SITES_DIR" != "" ]; then
    export SITE_COLLECTION_NAME=`basename ${RE_SITES_DIR}`
fi
# export SITE_COLLECTION_PREFIX=${RE_SITES_DIR}/${SITE_COLLECTION_NAME}.*.filtering_sites
export SITE_COLLECTION_PREFIX=${RE_SITES_DIR}/*.filtering_sites
export SITE_COLLECTION_SITES=`echo ${SITE_COLLECTION_PREFIX}.txt.gz 2>/dev/null`
export SITE_COLLECTION_BGZ=`echo ${SITE_COLLECTION_PREFIX}.txt.bgz 2>/dev/null`
export SITE_CHROM_DATA=`echo ${SITE_COLLECTION_PREFIX}.index.txt`
export CLOSEST_SITE_LOOKUP=`echo ${SITE_COLLECTION_PREFIX}.closest_site`
export SITE_DATA_LOOKUP=`echo ${SITE_COLLECTION_PREFIX}.site_data`

# SV extract file paths
export EXTRACT_PREFIX=${DATA_XGENOME_PREFIX}.extract
export PROPER_FRAGMENTS_PREFIX=${EXTRACT_PREFIX}.proper_fragments
export ANOMALOUS_SEQUENCE_EDGES=${EXTRACT_PREFIX}.anomalous_edges.sequences.txt.gz
export KEPT_DUPLICATES_FILE=${EXTRACT_PREFIX}.kept_duplicates.txt # ONT only, used to construct ANOMALOUS_MOLECULE_EDGES
export DISCARDED_DUPLICATES_FILE=${EXTRACT_PREFIX}.discarded_duplicates.txt
export ANOMALOUS_MOLECULE_EDGES=${EXTRACT_PREFIX}.anomalous_edges.molecules.txt.gz # ONT only
export ANOMALOUS_CONTIG_EDGES=${EXTRACT_PREFIX}.anomalous_edges.contigs.txt.gz
export PROPER_CONTIG_EDGES=${EXTRACT_PREFIX}.proper_edges.contigs.txt.gz

