# MDI GitHub Continuous Integration Action to build 
# a suite-level Singularity/Apptainer pipelines container image
# an push it to the GitHub Packages container registry

name: build pipelines container
on:
  # trigger on the first tags of a major or minor release, but not patch releases (e.g., v1.2.0 but not v1.2.1)
  push:
    tags: [ 'v[0-9]+.[0-9]+.0' ] # MDI repos expect v.#.#.# as semantic versions

permissions:
  contents: read
  packages: write

jobs:
  build-linux:
    runs-on: ubuntu-latest

    env:
      RUN_COMMAND: hf3 # or the suite short name if ./run was renamed

    steps:
      # checkout this tool suite
      - uses: actions/checkout@v6

      - name: Install Singularity/Apptainer
        run: |
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt-get update
          sudo apt-get install -y apptainer

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install MDI and build container image
        run: |
          export SKIP_MDI_APPS_INSTALL=1
          export FORCE_CONTAINER_BUILD=1
          export IS_GITHUB_ACTION=1
          ./install.sh --yes
          ./$RUN_COMMAND build --suite ${{ github.repository }} --container-type pipelines

      - name: Push container image to registry
        run: |
          SUITE_NAME=${{ github.repository }}
          SUITE_NAME=${SUITE_NAME#*/}
          LC_SUITE_NAME=${SUITE_NAME,,}
          VERSION_TAG=${{ github.ref_name }}
          MAJOR_MINOR_VERSION=${VERSION_TAG%.*}
          SIF_FILE=./mdi/containers/${LC_SUITE_NAME}/${LC_SUITE_NAME}-${MAJOR_MINOR_VERSION}.sif
          URI=oras://ghcr.io/${{ github.repository_owner }}/${LC_SUITE_NAME}:${MAJOR_MINOR_VERSION}
          echo "SIF_FILE: "$SIF_FILE
          echo "ORAS URI: "$URI
          singularity push ${SIF_FILE} ${URI}
